### ISSUE TITLE
KeOps as Backend ?

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1004]
KeOps Library could be another interesting Backend. Here is the JMLR paper  [Kernel Operations on the GPU, with Autodiff, without Memory Overflows](https://jmlr.org/papers/volume22/20-275/20-275.pdf) and Github Link [KeOps](https://github.com/getkeops/keops) and Python Interface [PyKeOps](https://github.com/getkeops/keops/tree/master/pykeops) .  Main Motive of the library (Quoting)

>  By providing cutting edge support for a wide range of important but “non-Euclidean” computations, we hope to stimulate research in computational mathematics and geometric data analysis

   Seems their Main selling point is performing various reduction operations on scale of Millions extremely efficiently and crucially without memory overflows. Following is what they claim

> Compared with a PyTorch GPU baseline, KeOps provides a x10-x100 speed-up on a wide range of geometric applications, from kernel methods to geometric deep learning.

Benchmark from the paper for computation of Gaussian Kernel Matrix Vector Product  

![image](https://user-images.githubusercontent.com/73220310/118272230-ef464a80-b4df-11eb-9f0d-70c0f81b6bd1.png)

They have some benchmarks here too http://www.kernel-operations.io/keops/_auto_benchmarks/index.html

**Comment by luisfpereira** [comment]
`keops` should definitely be considered, but not as a backend, as it is based on lazy evaluations (meaning it behaves in a completely different manner wrt to other backends). First place to try it out may be `discrete_surfaces`.
