### ISSUE TITLE
Frechet Mean returning poor result for n=2

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1010]
consider 

```
EULER = gs.exp(1.)
point_a = gs.array([[[EULER ** 2, 0], [0, 1]],
                             [[1, 0], [0, 1]]])
metric = SPDMetricAffine(n=2)
mean_estimator = FrechetMean(metric=metric, max_iter=1000, point_type='matrix')
mean = mean_estimator.fit(points_a).estimate_
print(mean)
```

```
[[4.19452805 0.        ]
 [0.         1.        ]]
```

under affine metric we can compute the frechet mean in closed form when number of samples is 2. It is essentially C_1#_{1/2}C_2

```
from scipy.linalg import fractional_matrix_power
M_hf      = fractional_matrix_power(points_a[0],0.5)
M_nhf     = fractional_matrix_power(points_a[0],-0.5)
temp      = M_nhf @ points_a[1] @ M_nhf
temp_pow  = fractional_matrix_power(temp,1/2)
M_current = M_hf @ temp_pow @ M_hf
print(M_current)
```

```
[[2.71828183 0.        ]
 [0.         1.        ]]
```

This is causing issue in  #1003. Should we handle the case separately when $n=2$ for `SPDMetricAffine ?

**Comment by ninamiolane** [comment]
@SaitejaUtpala could you share the math computations that led to the closed form of the Frechet mean for n=2? I am also not sure to follow your second code snippet.

Any input on this @ythanwerdas @nguigs ? This is unfortunately blocking PR #1003 .

**Comment by nguigs** [comment]
> @SaitejaUtpala could you share the math computations that led to the closed form of the Frechet mean for n=2? I am also not sure to follow your second code snippet.

This is just the middle of the affine invariant geodesic 

> Any input on this @ythanwerdas @nguigs ? This is unfortunately blocking PR #1003 .

Yes, the problem is in fact for any number of samples because the metric is found linear in these lines.

https://github.com/geomstats/geomstats/blob/0040b7ef6f9b1e68f8c275d1b84c5567f17eec7a/geomstats/learning/frechet_mean.py#L411-L415

I will fix this

**Comment by SaitejaUtpala** [comment]
@nguigs . I think this reflects bad unit tests. This should have been detected in first place by testing. For example, current test for frechet mean on spd-space is following. Samples considered are [point, point], So I think that is the reason it didn't detect  . Re-opened this issue to improve testing for this. 

```
 def test_estimate_spd(self):
        point = SPDMatrices(3).random_point()
        points = gs.array([point, point])
        mean = FrechetMean(metric=SPDMetricAffine(3), point_type='matrix')
        mean.fit(X=points)
        result = mean.estimate_
        expected = point
        self.assertAllClose(expected, result)
```

**Comment by SaitejaUtpala** [comment]
@ninamiolane  @nguigs  Oops. My bad just looked at the PR #1013 . Nicolas has already taken this account I guess..

**Comment by nguigs** [comment]
> I think this reflects bad unit tests. 

You're right, maybe the test I added should run on more spaces ( I checked manually that it did)

**Comment by SaitejaUtpala** [comment]
@nguigs, also for SPD currently we are not testing frechet mean with adaptive GD ?
