### ISSUE TITLE
Let's use auto-formatting tools like isort, black

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1023]
Currently, fair amount of time(developers' and reviewers') is spent about linting. Also, some contributors are finding difficult to fit into 79-characters-only-per-line rule (see #1014 ). Here is the excellent talk, where creator of black mentions  why 79 characters is not good.  https://www.youtube.com/watch?v=esZLCuWs_2Y. Really Fascinating talk, I would totally recommend it (He is currently python release manager, btw). Here is his main argument,  when he was Software Engineer at Facebook and he conducted large scale study about characters restriction and what he found is that  restricting lines to 79 characters made files long and also resulted in ugly formatting . This behavior is continued until ~88 characters and after which it was stable. So he decided to use 88 characters as limit in Black. Many observations like these is the reason it received huge adoption from Python community. I think we should use Black.

**Comment by ninamiolane** [comment]
I agree! Actually, DeepSource should allow us to do this automatically, because DeepSource has `Transformers` that can use isort and black to automatically format the code. Should I try to set it up?

**Comment by SaitejaUtpala** [comment]
ooh nice. Didn't know that deepsource has such functionality. yup let's set it up

**Comment by nguigs** [comment]
I'm not sure I agree with the way the code is being reformatted in #1036, especially with arguments being spread on different lines. This results in even longer scripts.
Moreover, how come the PR opened by black/isort fail some test on linting?

**Comment by SaitejaUtpala** [comment]
> I'm not sure I agree with the way the code is being reformatted in #1036, especially with arguments being spread on different lines. This results in even longer scripts.

@nguigs  Actually quite the contrary :). If you see the PR opened by deepsource in #1025 . formatting with Black reduced  number of lines from 14,024 to 13,648. Same is true for #1036 as well. Here is another reason which I think we should spread arguments one per line (black does this when it cannot put entire function header in single line) **Type annotations**.  Example see here for definition of  conv module in pytorch https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py (lines from 67 to 80)

> Moreover, how come the PR opened by black/isort fail some test on linting?

Because black and flake8 have different rules for formatting.
