### ISSUE TITLE
shall the n_jobs of ProductManifold be passed to its metric?

### ISSUE THREAD

**Issue by doublestrong** [geomstats/geomstats#1029]
Hi,

I am trying to speed up exponential and logarithmic maps of my product manifold by joblib. I defined n_jobs in my ProductManifold to 5 and do computations like ProductManifold.metric.exp(...). I checked the n_jobs in ProductRiemannianMetric and it was still the default value 1. The issue is that the n_jobs I defined for ProductManifold has not been passed to ProductRiemannianMetric.

https://github.com/geomstats/geomstats/blob/55d2e3ed252e46cf980f30d400acd4287867ad9f/geomstats/geometry/product_manifold.py#L54

Maybe line 53-54 in the link above can be:
`        metric = ProductRiemannianMetric(
            metrics, default_point_type=default_point_type,n_jobs=n_jobs)`

With the modification, I can see the difference between different n_jobs defined in ProductManifold:
![joblib_SE](https://user-images.githubusercontent.com/5796120/122151388-79f6ce00-ce2d-11eb-9a04-784ccfa5c65d.png)

A follow-up question I have is in what circumstances the joblib feature can earn us faster log, exp, and inner_product computations?

**Comment by nguigs** [comment]
Thank you for spotting this caveat!
As your plot suggests, n_jobs > 1 is useful if the computations relative to one metric are long enough. For example if you use a different invariant metric on SE(n) (by setting the metric matrix to a diagonal matrix different from identity), exp and logs are computed with numerical schemes that are quite slow, so parallelism helps

**Comment by doublestrong** [comment]
Thanks a lot!
