### ISSUE TITLE
can't find arctan2 in backend

### ISSUE THREAD

**Issue by erbas** [geomstats/geomstats#103]
Running the example, `loss_and_gradient_se3.py` gives the following output:

> (py35) $ python example_loss_and_gradient_se3.py 
> Using numpy backend
> The loss between the rotation vectors is: 3.7191479601637325
> The riemannian gradient is: [ 1.33950627 -0.55349447 -0.29312899  2.          2.          2.        ]
> Traceback (most recent call last):
>   File "example_loss_and_gradient_se3.py", line 135, in <module>
>     main()
>   File "example_loss_and_gradient_se3.py", line 127, in main
>     representation='quaternion')
>   File "example_loss_and_gradient_se3.py", line 73, in grad
>     quat_arctan2 = gs.arctan2(quat_vec_norm, quat_scalar)
> AttributeError: module 'geomstats.backend' has no attribute 'arctan2'

**Comment by johmathe** [comment]
You're probably trying to run the example with an older version of geomstats. You have two options:

1. Run the example from the root of the repository
2. Upgrade geomstats:

```bash
sudo pip3 uninstall geomstats
sudo python3 setup.py install
```

**Comment by erbas** [comment]
I should have mentioned, this was the first thing I did after installing geomstats. So I am running the latest version.

**Comment by johmathe** [comment]
Yes but the latest version doesn't run this example yet - we haven't released it yet so you wont be able to install it. That's why I recommended to install it via the setup.py script. We will release version 2.0 soon.
