### ISSUE TITLE
Add unit-tests for Python 3.9

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1070]
Python 3.9 is here and we are not testing on it. Some users are experiencing bugs with Python 3.9 that should be solved.

**Comment by vluzko** [comment]
Are there any sample bugs? None of the existing tests fail with python 3.9.

**Comment by nguigs** [comment]
This seems to have been done for backends autograd and numpy, what about pytorch and tensorflow?

**Comment by ninamiolane** [comment]
It's done!
