### ISSUE TITLE
Dead link to 'template unit-tests' in https://geomstats.github.io/contributing.html  

### ISSUE THREAD

**Issue by mortenapedersen** [geomstats/geomstats#1076]
Not a code-issue, but an issue about https://geomstats.github.io/contributing.html.

The current link to 'template unit-tests' is 

https://github.com/geomstats/geomstats/tree/master/tests/test__my_manifold.py

I guess it should be changed to 

https://github.com/geomstats/geomstats/blob/master/tests/tests_geomstats/test__my_manifold.py

**Comment by ninamiolane** [comment]
Thank you so much @mortenapedersen for spotting this 🎉 . Just fixed it.
