### ISSUE TITLE
Question regarding geomstats deep learning

### ISSUE THREAD

**Issue by NullCodex** [geomstats/geomstats#1081]
The applications for deeplearning with resnet and CIFAR has an example where the `Conv2D` takes in `kernel_manifold` as shown below:
```
    manifold = None
    if kernel_size == 3:
        manifold = Hypersphere(dimension=8)
    conv = Conv2D(num_filters,
                  kernel_size=kernel_size,
                  strides=strides,
                  padding='same',
                  kernel_initializer='he_normal',
                  kernel_manifold=manifold,
                  kernel_regularizer=l2(1e-4))
```

But this `kernel_manifold` is not a recognized argument to the layer. If we want to use geomstat with deeplearning how should we proceed? The deep learning applications were updated 3 years ago and I am not sure it works with the new tensorflow 2.0

**Comment by NullCodex** [comment]
After going through the documentation I see that I need to patch tensorflow variables but with Tensorflow 2 this is much more different. Is there a way I can use this without patching tensorflow? Can we sublcass `Conv2D`

**Comment by NullCodex** [comment]
Is it possible to get an update on this? Is it because I am missing certain details?

**Comment by ninamiolane** [comment]
Hi @NullCodex , so sorry for the late reply! 

As you noticed, the geomstats deep learning has been created 3 years ago. It has not been updated since: unfortunately, we chose not to maintain it anymore, because we do not have enough maintainers. 

Thus, there is little chance that it will work with tf 2.0 but you can try to adapt it!

Thanks for understanding!

**Comment by NullCodex** [comment]
Hi! I would be willing to try and adopt it for tf 2.0 but I am not sure the effort it will take. I was trying to understanding how the original worked but I am having difficulties with the task.

**Comment by luisfpereira** [comment]
I'm closing this because we ended up dropping `tensorflow` along the way (#1773). If interest raises on this again, please reopen the issue.
