### ISSUE TITLE
Error in parallel computing for information geometry notebook

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1083]
Error reported by Marc Lambert.

Upon execution of `mean.fit(points_plan)` within the information geometry notebook, the follopwing error is returned:

```
 AttributeError: Can't pickle local object 'DirichletMetric._geodesic_bvp.<locals>.path.<locals>.process_function'.
```
It could be related to the computations in parallel performed?

**Comment by nguigs** [comment]
The non pickable functions need to be wrapped by a decorator, see e.g.
https://github.com/geomstats/geomstats/blob/5fbc384fcf4b0123aadd52da4a8d49ec1701b57a/geomstats/geometry/riemannian_metric.py#L367-L375

**Comment by ninamiolane** [comment]
The function in `dirichlet.py` is currently implemented with `multiprocessing` and not `joblib`, so this didn't work right away.

By reformulating it with `joblib` (see code snippet below), it seems to work, but the timer should be put back, and the unit tests should be adapted too probably.

```
        def path(t):
            """Generate parameterized function for geodesic curve.

            Parameters
            ----------
            t : array-like, shape=[n_times,]
                Times at which to compute points of the geodesics.

            Returns
            -------
            geodesic : array-like, shape=[..., n_times, dim]
                Values of the geodesic at times t.
            """
            t = gs.to_ndarray(t, to_ndim=1)
            geod = []

            def initialize(point_0, point_1):
                """Initialize the solution of the boundary value problem."""
                lin_init = gs.zeros([2 * self.dim, n_steps])
                lin_init[:self.dim, :] = gs.transpose(
                    gs.linspace(point_0, point_1, n_steps))
                lin_init[self.dim:, :-1] = n_steps * (
                    lin_init[:self.dim, 1:] - lin_init[:self.dim, :-1])
                lin_init[self.dim:, -1] = lin_init[self.dim:, -2]
                return lin_init

            t_int = gs.linspace(0., 1., n_steps)
            fun_jac = jac if jacobian else None

            @joblib.delayed
            @joblib.wrap_non_picklable_objects
            def process_function(ip, ep):
                def bc(y0, y1, ip=ip, ep=ep):
                    return boundary_cond(y0, y1, ip, ep)
                solution = solve_bvp(
                    bvp, bc, t_int, initialize(ip, ep), fun_jac=fun_jac)
                solution_at_t = solution.sol(t)
                geodesic = solution_at_t[:self.dim, :]
                geod.append(gs.squeeze(gs.transpose(geodesic)))
                return geod[0]

            pool = joblib.Parallel(n_jobs=-1)
            geod = pool(process_function(ip, ep) for ip, ep in zip(initial_point, end_point))

            return geod[0] if len(initial_point) == 1 else gs.stack(geod)

        return path
```

**Comment by ninamiolane** [comment]
It seems that joblib has a timeout parameter, but it only works when there are multiple jobs:
https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html

However, in the case of 1 job, we can probably do the timeout manually, with `import time`, and `time.clock()`?
https://www.tutorialspoint.com/python/time_clock.htm

**Comment by alebrigant** [comment]
The function that I am trying to stop if it takes too long is the scipy.optimize function ```solve_bvp```, and so any line of code that I write after calling this function will not be able to stop it, unless I'm missing something. That's why I encapsulated the ```solve_bvp``` into a function ```process_function``` which I could start with ```.start()```, let run for a certain time using ```.join(max_time)``` and stop using ```.terminate()```.
