### ISSUE TITLE
get rid of all ellipsis notation in einsums

### ISSUE THREAD

**Issue by johmathe** [geomstats/geomstats#109]
We need to get rid of ellipsis notations in einsums for backends to love us back.

**Comment by ninamiolane** [comment]
@nguigs @opeltre this is when we deleted ellipsis notations. It might not be needed anymore with tensorflow and pytorch newer versions 🙏 or alternatively could at least be abstracted in the backends?

**Comment by opeltre** [comment]
Hmm I guess it could be done with some regex matching and would be really useful in enforcing correct vectorization behaviour...

**Comment by opeltre** [comment]
https://pytorch.org/docs/stable/torch.html#torch.einsum
einsum ellipsis should be ok according to the docs!

**Comment by opeltre** [comment]
was this fixed since the issue? quick tests could be done I guess :)

**Comment by ninamiolane** [comment]
Closing this, as we are bringing ellipsis back in the code, by extending torch and tf einsum in the backend when needed.
