### ISSUE TITLE
Installing via git results in error

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1123]
The command:
`pip3 install git+https://github.com/geomstats/geomstats.git`
results in:
```
 ERROR: Command errored out with exit status 1:
     command: /Users/ninamiolane/opt/anaconda3/envs/funcmaps/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/setup.py'"'"'; __file__='"'"'/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-pip-egg-info-co8un4en
         cwd: /private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/setup.py", line 10, in <module>
        geomstats = runpy.run_path(os.path.join(base_dir, 'geomstats', '__init__.py'))
      File "/Users/ninamiolane/opt/anaconda3/envs/funcmaps/lib/python3.9/runpy.py", line 268, in run_path
        return _run_module_code(code, init_globals, run_name,
      File "/Users/ninamiolane/opt/anaconda3/envs/funcmaps/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/Users/ninamiolane/opt/anaconda3/envs/funcmaps/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/geomstats/__init__.py", line 3, in <module>
        import geomstats._backend
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/geomstats/__init__.py", line 5, in <module>
        import geomstats.geometry.discrete_curves
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/geomstats/geometry/discrete_curves.py", line 6, in <module>
        import geomstats.backend as gs
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/geomstats/_backend/__init__.py", line 231, in load_module
        module = self._create_backend_module(_BACKEND)
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/geomstats/_backend/__init__.py", line 176, in _create_backend_module
        backend = self._import_backend(backend_name)
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/geomstats/_backend/__init__.py", line 170, in _import_backend
        from geomstats._backend import tensorflow as backend
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/geomstats/_backend/tensorflow/__init__.py", line 66, in <module>
        from . import random  # NOQA
      File "/private/var/folders/dz/k1hb2xr94k558sjs416njdp40000gn/T/pip-req-build-zv93in9z/geomstats/_backend/tensorflow/random.py", line 4, in <module>
        import tensorflow_probability as tfp
    ModuleNotFoundError: No module named 'tensorflow_probability'
    ----------------------------------------
WARNING: Discarding git+https://github.com/geomstats/geomstats.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by SwastiKh** [comment]
Hi!
I created a new conda environment using the `environments.yml` file from the repository.  Using the git command inside that environment successfully installed it. The command `pip3 install git+https://github.com/geomstats/geomstats.git` resulted in:

`Collecting git+https://github.com/geomstats/geomstats.git                                                                 Cloning https://github.com/geomstats/geomstats.git to c:\users\skhur\appdata\local\temp\pip-req-build-mgekazbc          Running command git clone -q https://github.com/geomstats/geomstats.git 'C:\Users\skhur\AppData\Local\Temp\pip-req-build-mgekazbc'                                                                                                              Resolved https://github.com/geomstats/geomstats.git to commit 3c2aaea7c1a3d156e4e5f7ad9a5018ed505f39fe                Requirement already satisfied: joblib>=0.14.1 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from geomstats==2.2.3) (1.0.1)                                                                                                              Requirement already satisfied: matplotlib>=3.3.4 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from geomstats==2.2.3) (3.4.3)                                                                                                           Requirement already satisfied: numpy>=1.18.1 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from geomstats==2.2.3) (1.21.2)                                                                                                              Requirement already satisfied: pandas>=1.1.5 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from geomstats==2.2.3) (1.3.2)                                                                                                               Requirement already satisfied: scikit-learn>=0.22.1 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from geomstats==2.2.3) (0.24.2)                                                                                                       Requirement already satisfied: scipy>=1.4.1 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from geomstats==2.2.3) (1.7.1)                                                                                                                Requirement already satisfied: cycler>=0.10 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from matplotlib>=3.3.4->geomstats==2.2.3) (0.10.0)                                                                                            Requirement already satisfied: kiwisolver>=1.0.1 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from matplotlib>=3.3.4->geomstats==2.2.3) (1.3.1)                                                                                        Requirement already satisfied: pyparsing>=2.2.1 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from matplotlib>=3.3.4->geomstats==2.2.3) (2.4.7)                                                                                         Requirement already satisfied: pillow>=6.2.0 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from matplotlib>=3.3.4->geomstats==2.2.3) (8.3.1)                                                                                            Requirement already satisfied: python-dateutil>=2.7 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from matplotlib>=3.3.4->geomstats==2.2.3) (2.8.2)                                                                                     Requirement already satisfied: six in c:\users\skhur\appdata\roaming\python\python38\site-packages (from cycler>=0.10->matplotlib>=3.3.4->geomstats==2.2.3) (1.14.0)                                                                            Requirement already satisfied: pytz>=2017.3 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from pandas>=1.1.5->geomstats==2.2.3) (2021.1)                                                                                                Requirement already satisfied: threadpoolctl>=2.0.0 in e:\anaconda3\envs\geomstats-3.8\lib\site-packages (from scikit-learn>=0.22.1->geomstats==2.2.3) (2.2.0)                                                                                  Building wheels for collected packages: geomstats                                                                         Building wheel for geomstats (setup.py) ... done                                                                        Created wheel for geomstats: filename=geomstats-2.2.3-py3-none-any.whl size=10116642 sha256=e7d6715e8e7f08b668364478bcc1eb90143df0554cbf340e5ff9e2d3815b359f                                                                                    Stored in directory: C:\Users\skhur\AppData\Local\Temp\pip-ephem-wheel-cache-c7dge32f\wheels\c1\18\96\0637d829ebefc4aa9e57006845538aa54f6c0e9619e6b56541                                                                                      Successfully built geomstats                                                                                            Installing collected packages: geomstats                                                                                Successfully installed geomstats-2.2.3  `

**Comment by ninamiolane** [comment]
Awesome, thank you so much for checking this 🙌  

I guessed this error came from a bad installation at the time of testing. Good job, let's close this then 🎉
