### ISSUE TITLE
parallel transport documentation

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1187]
currently parallel transport takes 

* tangent_vec_a (tangent vector at base point to be transported.)
* tangent_vec_b (tangent vector at base point, along which the parallel transport is computed)
* base_point ( point on the hypersphere)

but if someone has 
* point_a (point from which tangent vector is to transported)
* tangent vector (tangent vector at point_a)
* point_b (a point to which tangent vector at point_a is to be transported)

one has to use (tangent_vector, Log_{point_a} point_b , base_point). it's better to properly document this so that someone new can use it.

**Comment by ninamiolane** [comment]
Agreed! Additionally, tangent_vec_a and tangent_vec_b could be renamed to:
- tangent_vec
- tangent_vec_transport_direction
or something like this, because I am always confused which one is tangent vec a and which one is tangent vec b.

**Comment by nguigs** [comment]
Yes, we could also add the option to give an `end_point` instead of `tangent_vec_b`, but we would need to change the signature of the method
