### ISSUE TITLE
Add a feature that allows to scale metrics

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1267]
For a metric defined by `inner_product(tangent_vec_a, tangent_vec_b, base_point)`, add the possibility to get the same metric scaled by a scalar factor, i.e. `scaling * inner_product(tangent_vec_a, tangent_vec_b, base_point)`.

This could be implemented as:
-  a new class, called `ScaledMetric` that is constructed from the original metric class, and a scalar factor `scaling`.
- an optional `scaling=1.` parameter that is passed to the parent `RiemannianMetric` class, and inherited by its child classes (with a special care given to the child classes that override some methods).

**Comment by ninamiolane** [comment]
Note that the Riemannian log and exp will be the same than in the original (non-scaled) metric, but curvature and distance / inner will be scaled, as we adopt the convention that scales the metric and not the log.

**Comment by luisfpereira** [comment]
Solved in #1740.
