### ISSUE TITLE
Install backend using idiomatic python/pip syntax

### ISSUE THREAD

**Issue by xegulon** [geomstats/geomstats#1292]
# This is a feature request

I find the way of choosing the backend could be done better by using the pythonic syntax:

```bash
pip install geomstats[torch]
```

or

```bash
pip install geomstats[tensorflow]
```

By default, the installed backend would be numpy.

_Reference: https://stackoverflow.com/a/60307740/11348232_

It could also be useful to use this feature to have a nicer syntax for the  development environment setup command (which is currently `pip3 install -r opt-requirements.txt` and could become `pip install geomstats[dev]`).

**Comment by SaitejaUtpala** [comment]
@xegulon Hi. Good suggestion. Let us know if you want to work on this!

**Comment by SaitejaUtpala** [comment]
@xegulon Great! Looking forward to it. 

Setup is in https://github.com/geomstats/geomstats/blob/master/setup.py. 
Requirements in https://github.com/geomstats/geomstats/blob/master/opt-requirements.txt 
Backend module code is here https://github.com/geomstats/geomstats/blob/master/geomstats/_backend/__init__.py
