### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by chicken-biryani** [geomstats/geomstats#1433]
### Where should the content be modified?

In the repository.

### What should be modified?

--

### Additional information

We could either add our own code of conduct or we could adapt one. I.e https://www.contributor-covenant.org/ like organisations usually do.

**Comment by ninamiolane** [comment]
Contributor covenant sounds like a great idea. Any input on this @nguigs @SaitejaUtpala @lpereira95 ?
