### ISSUE TITLE
SpecialEuclideanMatrixCannonicalLeftMetric takes group as argument

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1435]
### Where should the content be modified?

https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/special_euclidean.py

### What should be modified?

currently `SpecialEuclideanMatrixCannonicalLeftMetric` takes `group` as argument. But it should take parameters of group  instead of group itself. 

### Additional information

This is what convention has been for other metrics

**Comment by nguigs** [comment]
I do not agree, `group` is necessary in every `InvariantMetric` for computations (e.g. tangent_translation) more than for parameters (like dim, point_type).

**Comment by luisfpereira** [comment]
This was definitely settled by #1836.
