### ISSUE TITLE
Grasmannian is not  working when n=p

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1438]
### Where should the content be modified?

https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/grassmannian.py

### What should be modified?

Grasmannian(2,2) and more generally Grasmannian(n, n) for any n

**Comment by nguigs** [comment]
This is expected! With p=n, this space is reduced to a point and is not a manifold. An error is raised as the dimension is 0. It could be overridden to say explicitly to the user that p < n is expected.

**Comment by SaitejaUtpala** [comment]
@nguigs well the error doesn't say so 

```
 if k > n:
            raise ValueError(
                "k <= n is required: k-dimensional subspaces in n dimensions."
            )
```
