### ISSUE TITLE
Discrete Curves doesn't have projection 

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1482]
### Where should the content be modified?

https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/discrete_curves.py

### What should be modified?

```
from geomstats.geometry.discrete_curves import DiscreteCurves
from geomstats.geometry.hypersphere import Hypersphere
DiscreteCurves(Hypersphere(2)).projection
```

### Additional information
N/A

**Comment by ninamiolane** [comment]
This has been fixed by #1576
