### ISSUE TITLE
Discrete Curves SRV metrics geodesic doesn't follow geodesic signature

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1484]
### Where should the content be modified?

https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/discrete_curves.py

### What should be modified?

`def geodesic(self, initial_curve, end_curve=None, initial_tangent_vec=None):` is the current signature which is not something that is followed everywhere

**Comment by ninamiolane** [comment]
Fixed by PR #1632
