### ISSUE TITLE
ClosedDiscreteCurves doesn't have projection

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#1485]
### Where should the content be modified?

https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/discrete_curves.py

### What should be modified?

```
from geomstats.geometry.discrete_curves import ClosedDiscreteCurves
from geomstats.geometry.hypersphere import Hypersphere
ClosedDiscreteCurves(Hypersphere(2)).projection
```

**Comment by ninamiolane** [comment]
Closed curve has projection now.
