### ISSUE TITLE
autodiff fails on svd in matrices.py

### ISSUE THREAD

**Issue by ambellan** [geomstats/geomstats#1545]
Dear geomstats team,

this issue is a copy of [challenge-iclr-2022-issue-8](https://github.com/geomstats/challenge-iclr-2022/issues/8) originally reported by  [Christoph](https://github.com/vontycowicz) (see original text below).

In the meantime the svd-call was moved from align in pre_spape.py to align_matrices in mratices.py, the issue itself however, remains.

Best regards,
Felix

<<<<<
Dear geomstats team,

we are trying to perform geodesic regression in Kendall shape space but encountered the issue that the current implementation is not compatible with autodiff functionality.
In particular, the align method in geomstats/geometry/pre_shape.py employs singular value decomposition for which autodiff fails if a full set of left/right singular vectors are requested.
However, providing the flag 'full_matrices=False' avoids this pitfall and should yield the same alignment.

We added the flag and, indeed, are now able to run regression.
We will submit the modified pre_shape.py along with our project s.t. it does not rely on short notice updates of geomstats.

Best regards,
Christoph
<<<<<

**Comment by ambellan** [comment]
Dear geomstats team,

as also already written in the original issue a feasible solution is to simply add the flag 'full_matrices=False' to the svd call.

Best, Felix

**Comment by lpereira95** [comment]
Solved in #1546.
