### ISSUE TITLE
Inconsistent variable name for "rank" of Grassmannian manifolds

### ISSUE THREAD

**Issue by p16i** [geomstats/geomstats#1557]
### Where should the content be modified?

https://geomstats.github.io/api/geometry.html#geomstats.geometry.grassmannian.GrassmannianCanonicalMetric

### What should be modified?

In the description of the Grassmannian manifold, we use $k$ to represent the rank.

But, the metric class uses $p$ for the rank, and the docstring of the construction is $k$

https://github.com/geomstats/geomstats/blob/5fb48353b6e86c7ca885c723d6bb65c38df15855/geomstats/geometry/grassmannian.py#L310

https://github.com/geomstats/geomstats/blob/5fb48353b6e86c7ca885c723d6bb65c38df15855/geomstats/geometry/grassmannian.py#L306

IMHO, the simplest way to fix this is to fix the docstring to use $p$ but this might later lead to a confusion because our explanation about Grassmannian manifolds use $\text{Gr}(n, k)$. 

Therefore, a more proper way to fix it is to refactor the Grassmannian metric class to use $k$.

What do you think?

**Comment by luisfpereira** [comment]
This was solved in #1586.
