### ISSUE TITLE
PyTorch Examples?

### ISSUE THREAD

**Issue by ningxia** [geomstats/geomstats#158]
Thanks.

**Comment by simama** [comment]
Does the `loss_and_gradient_se3.py` example work for you with PyTorch backend?
I get:
`RuntimeError: Trying to resize storage that is not resizable at /pytorch/aten/src/TH/generic/THStorage.c:183`

**Comment by krstp** [comment]
Similar error here, in my case running this case:
https://nbviewer.jupyter.org/github/kaushaltrivedi/bert-toxic-comments-multilabel/blob/master/toxic-bert-multilabel-classification.ipynb

While fitting, a single epoch completes and quits with:

RuntimeError: Tryin gto resize storage that is not resizable at /pytorch/aten/src/TH/THStorageFunctions.cpp

Did you find any solution?

**Comment by ninamiolane** [comment]
Thank you for your interest! We are still working on the pytorch backend and examples and will update the codebase when we get them running.

**Comment by ninamiolane** [comment]
@ningxia sorry for the delay in addressing this! These examples should now work with pytorch backend.

Do not hesitate to be in touch again if you are encountering issues!
