### ISSUE TITLE
Bug: Segmentation fault for FrechetMean with SRV metric (curves) in pytorch

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1618]
### Describe the bug

The Frechet mean gives "Segmentation fault: 11" when computed with the SRV metric on a large dataset of curves, with many sampling points.

The code to reproduce is below.

Notes:
- It works in numpy. 
- It works for n_sampling_points=10 and n_samples=10
- It works within test_frechet_mean, see PR #1617 that adds tests with a high number of sampling points.

### Steps/Code to Reproduce

```
import os
os.environ["GEOMSTATS_BACKEND"] = "pytorch"
import geomstats.backend as gs

from geomstats.geometry.discrete_curves import R2, DiscreteCurves
from geomstats.learning.frechet_mean import FrechetMean

curves_2d_many_sampling_points = DiscreteCurves(R2, k_sampling_points=100)
metric = curves_2d_many_sampling_points.srv_metric

points = curves_2d_many_sampling_points.random_point(n_samples=100)

mean = FrechetMean(metric=metric, method="default")
mean.fit(points)
```

### Expected Behaviour

Give Frechet mean.

### Actual Behaviour

Segmentation fault 11

### Your environment

```shell
- python=3.8
  - pip
  - matplotlib>=3.5.1
  - pip:
    - autograd
    - git+https://github.com/geomstats/geomstats.git
    - jupyter
    - mat73
    - numba
    - numpy>=1.23.0
    - scikit-image
    - torch>=1.11
    - opencv-python

Geomstats 2.5.0 installed from master
Python 3.8.13
```

**Comment by luisfpereira** [comment]
@ninamiolane, I'm unable to replicate this. I think it relates somehow with [this](https://github.com/geomstats/geomstats/issues/1283#issuecomment-1630832101) comment. I'm closing. Please reopen again if the problem somehow persists.
