### ISSUE TITLE
Bug: `gs.array` is unaffected by the global tensor type for torch backend

### ISSUE THREAD

**Issue by miguelgondu** [geomstats/geomstats#1626]
### Describe the bug

I am trying to move a training pipeline I have implemented on top of geomstats to `cuda`, and have faced issues similar to previous ones raised in #843 and #1476.

In #1476, they state that a workaround is to define a global tensor type like `torch.cuda.FloatTensor`. I have found that this doesn't work when some algorithms instantiate the tensors using `gs.array`. My guess is that the implementation in `def array(vals...)` is forgetting to move the array to the proper global device and default dtype.

Unfortunately, this makes it impossible to work with some of geomstats tools if you want to perform your operations in the GPU using torch. This issue was raised when [I was trying to compute `log`s in the `Hypersphere` metric, since the local operations are performed using `gs.array` in the algebra utilities](https://github.com/geomstats/geomstats/blob/8d603a0fb042ea44c8c90dc1dca7cbf7af92dd9b/geomstats/algebra_utils.py#L136).

### Steps/Code to Reproduce

```python
# Using PyTorch as a backend for geomstats.

import geomstats
import geomstats.backend as gs

import torch

torch.set_default_tensor_type("torch.cuda.DoubleTensor")

a = torch.Tensor([0.0, 0.0])
b = gs.array([0.0, 0.0])

print(a.device, b.device)
```

### Expected Behaviour

The printed devices are the same, and `cuda` if it is available.

### Actual Behaviour

The tensor `b` is living in the CPU.

### Your environment

```shell
- `geomstats=2.5.0`
- `torch=1.12.1+cu116`
- Running on Ubuntu 20.04.
- `CUDA=11.7`
- `NVidia-driver=515.65.01`
```

**Comment by luisfpereira** [comment]
@miguelgondu, somewhere along the way we solved this issue. Now it works as expected.

**Comment by miguelgondu** [comment]
Hi Luís, thanks for the help!

**Comment by FanmengWang** [comment]
hi 
I meet the same problem with "geomstats-2.8.0", how to solve it?

`import geomstats
import geomstats.backend as gs

import torch

torch.set_default_tensor_type("torch.cuda.DoubleTensor")

a = torch.Tensor([0.0, 0.0])
b = gs.array([0.0, 0.0])

print(a.device, b.device)`

AttributeError: 'numpy.ndarray' object has no attribute 'device'

**Comment by miguelgondu** [comment]
Hi @FanmengWang,

Are you using the `torch` backend? You can set it up by defining an environment variable `GEOMSTATS_BACKEND=pytorch`. Check [this page in the docs](https://geomstats.github.io/getting_started/first-steps.html).

If you're not acquainted with env. variables, I'd be happy to elaborate further.

**Comment by FanmengWang** [comment]
Hi @miguelgondu 
Thank you for your assistance with my issue sincerely. I have successfully resolved this problem. 
Best regards,
