### ISSUE TITLE
Remove support for tensorflow tests

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1690]
### Where should the content be modified?

.github/workflow/test.yml

### What should be modified?

Having tensorflow backend brings a lot of complexity to the code, hurting its readability, and preventing new contributors to easily join the project.

After talking with @lpereira95 , @ballerin , @alebrigant , @annacalissano , we feel that the best way forward is to stop testing in tf.

One possible open question: while we remove tests in tf, do we want to keep the tf backend?

Keeping it could be good: 
- for backward compatibility, and 
- for users who would be running geomstats in tf at their own risks.

**Comment by lpereira95** [comment]
For me removing tests also means removing backend (things will not work for sure after we stop testing).

Backward compatibility hasn't yet been an issue for geomstats... people can still use older versions of the code with tensorflow.

**Comment by luisfpereira** [comment]
Solved in #1778.

**Comment by luisfpereira** [comment]
Solved in #1778.
