### ISSUE TITLE
`Hermitian` CDTYPE

### ISSUE THREAD

**Issue by lpereira95** [geomstats/geomstats#1696]
In `Hermitian` we should not create `CDTYPE` once and then use it everywhere as it will not be updated when changing backend cdtype.

Why? Because `gs.get_default_dtype` returns an immutable type.

Why have we designed for this behavior? Because if `gs.get_default_dtype` returned a mutable object, we would provide different ways of changing `dtype` (which would break the backend expected behavior).  

How can I see this problem?

```python
import geomstats.backend

from geomstats.geometry import hermitian

gs.get_default_cdtype()
# dtype('complex128')

hermitian.CDTYPE
# dtype('complex128')

gs.set_default_dtype('float32')

gs.get_default_cdtype()
# dtype('complex64')

hermitian.CDTYPE
# dtype('complex128')
```

@YannCabanes it may interest you for future implementations. (I'll address this)

**Comment by YannCabanes** [comment]
Hello @lpereira95,
So we should use `gs.get_default_cdtype()` instead of CDTYPE in hermitian.py?
I guess that I also have to modify the PR adding Siegel (#1687) and the PR adding the HPD matrices (#1682).
So we can use CDTYPE only in the test files, right?

**Comment by YannCabanes** [comment]
If we replace `CDTYPE` by `gs.get_default_cdtype()` in the file hermitian.py, it solves the problem.
Indeed, we then have:

`import geomstats.backend as gs
# INFO: Using numpy backend

from geomstats.geometry.hermitian import Hermitian

gs.get_default_cdtype()
# dtype('complex128')

Hermitian(2).get_identity().dtype
# dtype('complex128')

gs.set_default_dtype('float32')
# dtype('float32')

gs.get_default_cdtype()
# dtype('complex64')

Hermitian(2).get_identity().dtype
# dtype('complex64')

gs.set_default_dtype('float64')
# dtype('float64')

gs.get_default_cdtype()
# dtype('complex128')

Hermitian(2).get_identity().dtype
# dtype('complex128')`

**Comment by YannCabanes** [comment]
So we have to remove `CDTYPE = gs.get_default_cdtype()` from hermitian.py, complex_manifold.py and complex_riemannian_metric.py.
And also from the current PRs adding Siegel (https://github.com/geomstats/geomstats/pull/1687) and the PR adding the HPD matrices (https://github.com/geomstats/geomstats/pull/1682).

**Comment by lpereira95** [comment]
Thanks @YannCabanes!

in fact in the tests it is OK to do that because the backend will not change. but in the other parts of the code it needs to load everytime (which is not adding overhead anyway).

Thanks for addressing this!
