### ISSUE TITLE
Bug: module 'geomstats.backend' has no attribute 'matvec'

### ISSUE THREAD

**Issue by huzhenbang** [geomstats/geomstats#1780]
### Describe the bug

module 'geomstats.backend' has no attribute 'matvec'

I run notebook example [09_practical_methods__implement_your_own_riemannian_geometry.ipynb](http://localhost:8888/notebooks/09_practical_methods__implement_your_own_riemannian_geometry.ipynb).

install steps as follow:
1.conda install -c conda-forge geomstats
2.pip install geomstats[autograd]
3.pip install geomstats[tensorflow]

set 

I have 

AttributeError                            Traceback (most recent call last)
Cell In[9], line 6
      3 # We immerse the points and the tangent vector in R^3
      5 immersed_point_a = sphere_immersion(point_a)
----> 6 immersed_tangent_vec = gs.matvec(jac_sphere_immersion(point_a), tangent_vec)
      7 immersed_end_point = sphere_immersion(end_point)
      9 # We plot our results

AttributeError: module 'geomstats.backend' has no attribute 'matvec'

### Steps/Code to Reproduce

immersed_point_a = sphere_immersion(point_a)
immersed_tangent_vec = gs.matvec(jac_sphere_immersion(point_a), tangent_vec)
immersed_end_point = sphere_immersion(end_point)

### Expected Behaviour

It should work like demo.

### Actual Behaviour

report bugs

### Your environment

```shell
I have tried windows and linux.
```

**Comment by huzhenbang** [comment]
I don't find any infomation about matvec from https://geomstats.github.io/api/backend.html#.

**Comment by ninamiolane** [comment]
Hi @huzhenbang thank you for your interest! Did you try installing geomstats directly from github?

```
git clone https://github.com/geomstats/geomstats.git
cd geomstats
pip3 install .
```
I am suspecting that mat_vec appears in the latest version of geomstats, which has not been pushed to pypi yet.

Hope it can help!

**Comment by huzhenbang** [comment]
Thanks. It works.
