### ISSUE TITLE
Bug: How set the "export GEOMSTATS_BACKEND=autograd " the default backend in windows environment

### ISSUE THREAD

**Issue by BNUWUXI** [geomstats/geomstats#1841]
### Describe the bug

I run the Tutorials "Implement your own Riemannian Geometry" in Jupyter on the Windows enviroment. 

But when I run the code line "jac_sphere_immersion = gs.autodiff.jacobian(sphere_immersion)", I meet the error "RuntimeError: Automatic differentiation is not supported with numpy backend. Use autograd, pytorch or tensorflow backend instead. Change backend via the command export GEOMSTATS_BACKEND=autograd in a termina".

I wanna figure out how to solve this, to change the default backend in windows (I have tried run the set GEOMSTATS_BACKEND=autograd in terminal but this not work).

### Steps/Code to Reproduce

 the code line "jac_sphere_immersion = gs.autodiff.jacobian(sphere_immersion)"

### Expected Behaviour

To get the right ouput and not to get error

### Actual Behaviour

RuntimeError: Automatic differentiation is not supported with numpy backend. Use autograd, pytorch or tensorflow backend instead.

Change backend via the command export GEOMSTATS_BACKEND=autograd in a terminal.

### Your environment

```shell
Windows
-- with pytorch installed by pip
-- with autograd installed by pip
-- with numpy installed by pip
```

**Comment by luisfpereira** [comment]
@BNUWUXI you need to create an environment variable (see e.g. [this](https://www.computerhope.com/jargon/e/envivari.htm)). from the command line you can create it using `set`. I think it is also possible to create it manually (please google it if it is your preferred way).

what matters is that later the code `os.environ.get("GEOMSTATS_BACKEND")` gets something other than `None`, otherwise it uses `numpy`.

**Comment by BNUWUXI** [comment]
> @BNUWUXI you need to create an environment variable (see e.g. [this](https://www.computerhope.com/jargon/e/envivari.htm)). from the command line you can create it using `set`. I think it is also possible to create it manually (please google it if it is your preferred way).
> 
> what matters is that later the code `os.environ.get("GEOMSTATS_BACKEND")` gets something other than `None`, otherwise it uses `numpy`.

Thanks, I have solved this. Share my example on there,
-- code block below --
import os
import sys
import time
import warnings

sys.path.append(os.path.dirname(os.getcwd()))
warnings.filterwarnings("ignore")

os.environ["GEOMSTATS_BACKEND"] = "pytorch"
print(os.environ.get("GEOMSTATS_BACKEND"))
