### ISSUE TITLE
Bug:  metric.geodetic: floats not accepted as initial_ and end_point

### ISSUE THREAD

**Issue by federicocampo** [geomstats/geomstats#1843]
### Describe the bug

I have been reviewing the documentation found at https://hal.science/hal-03862556v1/file/parametric-ig-geomstats.pdf and attempting to reproduce the example on page 9 using the ExponentialDistribution manifold (I also tried with Binomial distribution, copy-pasting the script on this paper). However, when I try to run the script, I receive the error message "float object has no attribute shape."

To address this issue, I tried to convert the float values to numpy arrays using the code 

>> point_a, point_b = gs.array(point_a), gs.array(point_b)

but then I received a new error stating "Automatic differentiation is not supported with numpy backend, use autograd etc..."

To fix this, I set the autograd environment via "set GEOMSTAT_BACKEND=autograd" (I am using Windows). However, I then encountered a new error message that reads " 'float' object has no attribute 'flatten'."

Could you please advise me on how to resolve these issues? My goal is to understand what caused the initial error and successfully run the example script.

Thank you for your assistance

### Steps/Code to Reproduce

import geomstats.backend as gs
from geomstats.information_geometry.binomial import BinomialDistributions

manifold = BinomialDistributions(5)
point_a = .4
point_b = .7
times = gs.linspace(0, 1, 100)
geodesic = manifold.metric.geodesic(initial_point=point_a, end_point=point_b)(times)

### Expected Behaviour

No errors

### Actual Behaviour

AttributeError: 'float' object has no attribute 'shape' attribute

### Your environment

```shell
geomstat version 2.5.0
environment: windows terminal; colab jupyter notebook
```

**Comment by luisfpereira** [comment]
@federicocampo, for consistency we later decided to not allow floats to be used, so points should be represented as arrays. As main motivation, imagine `Euclidean(dim=dim)`. If `dim=2` a point is represented as a `(2,)`-array. If `dim=1` it is represented as a `(1,)`-array. Therefore, we avoid using floats (it also simplifies vectorizations).

A working code is

```python
manifold = BinomialDistributions(5)
point_a = gs.array([.4])
point_b = gs.array([.7])
times = gs.linspace(0, 1, 100)
geodesic = manifold.metric.geodesic(initial_point=point_a, end_point=point_b)(times)
```

@alebrigant, @ninamiolane should the hal documented be updated to reflect what we've decided?


Thanks for raising the question!

**Comment by luisfpereira** [comment]
which version are you using? if you install the one in `master` (e.g. `pip install git+https://github.com/geomstats/geomstats.git@master#egg=geomstats`) your code will work, with exception of last line (because you've already evaluated geodesic, so your geodesic is an array and not a function anymore).

**Comment by federicocampo** [comment]
Thank you @luisfpereira, you're right, the github version works properly, 
Previously I had it installed using only "pip install geomstats"

Many thanks again for your help!
