### ISSUE TITLE
Bug: Tutorial Shape Analysis of Cancer Cells - FrechetMean

### ISSUE THREAD

**Issue by AliToghani82** [geomstats/geomstats#1846]
### Describe the bug

I have been going through the Tutorial for Shape Analysis of Cancer Cells "https://geomstats.github.io/notebooks/11_real_world_applications__cell_shapes_analysis.html". I have been directly copying the code into jupyter notebook, and everything up to input 19 was with the expected output as was shown in the Tutorial.  We read the documentation and changed input 19 line "SRV_METRIC = CURVES_SPACE.srv_metric" to "SRV_METRIC = CURVES_SPACE.square_root_velocity_metric" and it worked up to input 23. At input 23, there is another error in which mean.fit(cell_shapes[:500]) seems to have a problem. I have attached the code and expted behaviour bellow. I have not changed anything else other than input 19, since input 19 was also giving an error. 

Thank you. 

### Steps/Code to Reproduce

Input 19:
from geomstats.geometry.discrete_curves import R2, DiscreteCurves, SRVMetric

CURVES_SPACE = DiscreteCurves(R2)
SRV_METRIC = CURVES_SPACE.srv_metric

geodesic = SRV_METRIC.geodesic(initial_point=cell_start, end_point=cell_end)

n_times = 30
times = gs.linspace(0.0, 1.0, n_times)
geod_points = geodesic(times)

------

Input 23:
from geomstats.learning.frechet_mean import FrechetMean

mean = FrechetMean(metric=SRV_METRIC, method="default")
mean.fit(cell_shapes[:500])

mean_estimate = mean.estimate_

plt.plot(mean_estimate[:, 0], mean_estimate[:, 1], "black");

### Expected Behaviour

Input 19:
should just pass

Input 23:
[https://geomstats.github.io/_images/notebooks_11_real_world_applications__cell_shapes_analysis_58_0.png](url)

### Actual Behaviour

Input 19:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14368/2228987475.py in <module>
      2 
      3 CURVES_SPACE = DiscreteCurves(R2)
----> 4 SRV_METRIC = CURVES_SPACE.srv_metric
      5 
      6 geodesic = SRV_METRIC.geodesic(initial_point=cell_start, end_point=cell_end)

AttributeError: 'DiscreteCurves' object has no attribute 'srv_metric'

Input 23:
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_14368/9101715.py in <module>
      2 
      3 mean = FrechetMean(metric=SRV_METRIC, method="default")
----> 4 mean.fit(cell_shapes[:500])
      5 
      6 mean_estimate = mean.estimate_

~\anaconda3\lib\site-packages\geomstats\learning\frechet_mean.py in fit(self, X, y, weights)
    552 
    553         elif self.method == "default":
--> 554             mean = _default_gradient_descent(
    555                 points=X,
    556                 weights=weights,

~\anaconda3\lib\site-packages\geomstats\learning\frechet_mean.py in _default_gradient_descent(points, metric, weights, max_iter, point_type, epsilon, init_step_size, verbose, init_point)
    131         var = gs.sum(metric.squared_norm(logs, mean) * weights) / gs.sum(weights)
    132 
--> 133         tangent_mean = gs.einsum(einsum_str, weights, logs)
    134         tangent_mean /= sum_weights
    135         norm = gs.linalg.norm(tangent_mean)

<__array_function__ internals> in einsum(*args, **kwargs)

~\anaconda3\lib\site-packages\numpy\core\einsumfunc.py in einsum(out, optimize, *operands, **kwargs)
   1359         if specified_out:
   1360             kwargs['out'] = out
-> 1361         return c_einsum(*operands, **kwargs)
   1362 
   1363     # Check the kwargs to avoid a more cryptic error later, without having to

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

### Your environment

```shell
Windows 11 - 64-bit operating system
Geomstat 2.5.0
```

**Comment by luisfpereira** [comment]
We've updated the notebook to be more consistent regarding the metric used. Notice we now do:

```python
CURVES_SPACE_SRV = DiscreteCurves(Euclidean(dim=2), k_sampling_points=200)

geodesic = CURVES_SPACE_SRV.metric.geodesic(initial_point=cell_start, end_point=cell_end)
```

This works because `SRVMetric` is the default metric of this space. We could also do:

```python
CURVES_SPACE_SRV = DiscreteCurves(Euclidean(dim=2), k_sampling_points=200, equip=False)
CURVES_SPACE_SRV.equip_with_metric(SRVMetric)

geodesic = CURVES_SPACE_SRV.metric.geodesic(initial_point=cell_start, end_point=cell_end)
```

In the case we want to equip the space with another metric, we just need to change the `equip_with_metric` line.

Hope this helps. Let me know if I can help further.
