### ISSUE TITLE
Bug: example MyInformationManifold

### ISSUE THREAD

**Issue by ftuerlinckx** [geomstats/geomstats#1905]
### Describe the bug

When executing the code for the Fisher-Rao metric of the ad hoc defined normal distributions and evaluating the Fisher-Rao metric matrix I(theta) at theta=(1,1), I get an error message that goes all the way to the integration.

### Steps/Code to Reproduce

```import geomstats.backend as gs
from geomstats.geometry.base import OpenSet
from geomstats.geometry.euclidean import Euclidean
from geomstats.geometry.riemannian_metric import RiemannianMetric
from geomstats.information_geometry.fisher_rao_metric import FisherRaoMetric
from geomstats.information_geometry.base import (
    InformationManifoldMixin,
)


class MyInformationManifold(InformationManifoldMixin):
    def __init__(self):
        self.dim = 2
    def point_to_pdf(self,point):
        means = point[..., 0]
        stds = point[..., 1]
        def pdf(x):
            constant = (1. / gs.sqrt(2*gs.pi*stds**2))
            return constant*gs.exp(-((x-means)**2)/(2*stds**2))
        return pdf
    
metric = FisherRaoMetric(
    space = MyInformationManifold(), support =(-10,10))
        
print(metric.metric_matrix(gs.array([1., 1.])))
```

### Expected Behaviour

As indicated in the paper Le Brigant et al. (2023):
```
array([[1.00000000e+00,1.11022302e-16], [1.11022302e-16, 2.00000000e+00]])
```

### Actual Behaviour

```
INFO: Using autograd backend
Traceback (most recent call last):
  File "c:\Users\u0019524\OneDrive - KU Leuven\Documents\InformationGeom\code\newclass.py", line 26, in <module>
    print(metric.metric_matrix(gs.array([1., 1.])))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\geomstats\information_geometry\fisher_rao_metric.py", line 105, in metric_matrix
    return quad_vec(_function_to_integrate, *self.support)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\integrate\_quad_vec.py", line 320, in quad_vec     
    ig, err, rnd = _quadrature(x1, x2, f, norm_func)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\integrate\_quad_vec.py", line 597, in _quadrature_gk21
    return _quadrature_gk(a, b, f, norm_func, x, w, v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\integrate\_quad_vec.py", line 498, in _quadrature_gk
    ff = f(c + h*x[i])
         ^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\geomstats\information_geometry\fisher_rao_metric.py", line 93, in _function_to_integrate
    ) = gs.autodiff.value_and_grad(pdf_x, to_numpy=True)(base_point)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\geomstats\_backend\autograd\autodiff.py", line 116, in _value_and_grad
    return _autograd.value_and_grad(func, argnum=argnums)(*x, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\autograd\wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\autograd\differential_operators.py", line 138, in value_and_grad
    vjp, ans = _make_vjp(fun, x)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\autograd\core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\autograd\tracer.py", line 10, in trace
    end_box = fun(start_box)
              ^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\autograd\wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\geomstats\information_geometry\fisher_rao_metric.py", line 86, in <lambda>
    return lambda point: gs.squeeze(self._space.point_to_pdf(point)(x), axis=-1)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\u0019524\AppData\Local\Programs\Python\Python311\Lib\site-packages\geomstats\_backend\_shared_numpy\__init__.py", line 87, in squeeze
    if x.shape[axis] != 1:
       ~~~~~~~^^^^^^
IndexError: tuple index out of range
```

### Your environment

```shell
Windows 10, Version 22H2
Python 3.11.6 64-bit
Geomstats autograd backend
```

**Comment by ftuerlinckx** [comment]
Because in calling the Fisher-Rao metric function, "information_manifold=" is not a valid argument (anymore), I used "space=" instead.

**Comment by luisfpereira** [comment]
Hi @ftuerlinckx. Recently we've made a change where we don't think about an isolated metric anymore, but always connect it to space. So the way we think about this case can be achieved with something like:

```python
import geomstats.backend as gs

from geomstats.information_geometry.fisher_rao_metric import FisherRaoMetric
from geomstats.information_geometry.normal import (
    UnivariateNormalDistributions,
)

space = UnivariateNormalDistributions(equip=False)

space.equip_with_metric(FisherRaoMetric, support=(-10, 10))

point = gs.array([1., 1])

space.metric.metric_matrix(point)
``` 

which gives back the result in the paper.

Notice also that for such simple cases as univariate normals, we have closed-form solutions. Therefore, a much more performant code can be obtained with:

```python
import geomstats.backend as gs

from geomstats.information_geometry.normal import (
    UnivariateNormalDistributions,
    UnivariateNormalDistributionsMetric,
)

space = UnivariateNormalDistributions(equip=False)
space.equip_with_metric(UnivariateNormalDistributionsMetric)

point = gs.array([1., 1])

space.metric.metric_matrix(point)
```


Please let me know if I can still be of any help.

**Comment by ftuerlinckx** [comment]
Hi Luís, that's very helpful. That works. However, the code relies on the preprogammed "UnivariateNormalDistributions" while I want to define my own parametric distribution.  Thanks. Francis

**Comment by ftuerlinckx** [comment]
Dear Luís,

thanks for your assistance. However, being new to Python (I have mainly used R), I still run into trouble.

Here is the code:
##$env:GEOMSTATS_BACKEND = "autograd"
import geomstats.backend as gs
from geomstats.geometry.base import OpenSet
from geomstats.geometry.euclidean import Euclidean
from geomstats.geometry.riemannian_metric import RiemannianMetric
from geomstats.information_geometry.fisher_rao_metric import FisherRaoMetric
from geomstats.geometry.poincare_half_space import PoincareHalfSpace
from geomstats.information_geometry.base import (
    InformationManifoldMixin,
)

class MyInformationManifold(InformationManifoldMixin, PoincareHalfSpace):
    def __init__(self, equip=True):
        super().__init__(dim=2, support_shape=(), equip=equip)

    def point_to_pdf(self,point):
        means = point[..., 0]
        stds = point[..., 1]
        def pdf(x):
            x = gs.reshape(gs.array(x), (-1,))
            constant = (1. / gs.sqrt(2*gs.pi*stds**2))
            return constant*gs.exp(-((x-means)**2)/(2*stds**2))
        return pdf

space = MyInformationManifold(equip = False)
space.equip_with_metric(FisherRaoMetric, support=(-10, 10))
point = gs.array([1., 1])
print(space.metric.metric_matrix(point))

I still get an error message:
Traceback (most recent call last):
  File "c:\Users\u0019524\OneDrive - KU Leuven\Documents\InformationGeom\code\newclass.py", line 26, in <module>
    space = MyInformationManifold(equip = False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\u0019524\OneDrive - KU Leuven\Documents\InformationGeom\code\newclass.py", line 15, in __init__
    super().__init__(dim=2, support_shape=(), equip=equip)
TypeError: PoincareHalfSpace.__init__() got an unexpected keyword argument 'support_shape'

Thanks for helping me out!

Regards
francis

**Comment by luisfpereira** [comment]
You probably need to run with version in `main`, as we recently made changes in `information_geometry` that we not published yet.

You can install it with: `pip install git+https://github.com/geomstats/geomstats.git@main#egg=geomstats`

**Comment by ftuerlinckx** [comment]
Dear Luis,

sorry for the spam, but have you been able to look at my question below? (I ask it because your software is really what I need for a current project I am working on.)

Thanks a lot!

Kind regards,
francis

From: Francis Tuerlinckx
Sent: maandag 4 december 2023 10:44
To: geomstats/geomstats ***@***.***>; geomstats/geomstats ***@***.***>
Cc: ftuerlinckx ***@***.***>; Mention ***@***.***>
Subject: RE: [geomstats/geomstats] Bug: example MyInformationManifold (Issue #1905)

Dear Luis,

Thanks a lot. Sorry for the late reply but I had to focus on other things. In the meantime I reinstalled the geomstats package (as you indicated below) but it does not resolve the error. Here is all my code:

## pip install -I ***@***.***#egg=geomstats --user
## $Env:GEOMSTATS_BACKEND = "autograd"
## in prompt: setx GEOMSTATS_BACKEND "autograd"

import geomstats.backend as gs
from geomstats.geometry.base import OpenSet
from geomstats.geometry.euclidean import Euclidean
from geomstats.geometry.riemannian_metric import RiemannianMetric
from geomstats.information_geometry.fisher_rao_metric import FisherRaoMetric
from geomstats.geometry.poincare_half_space import PoincareHalfSpace
from geomstats.information_geometry.base import (
    InformationManifoldMixin,
)

class MyInformationManifold(InformationManifoldMixin, PoincareHalfSpace):
    def __init__(self, equip=True):
        super().__init__(dim=2, support_shape=(), equip=equip)

    def point_to_pdf(self,point):
        means = point[..., 0]
        stds = point[..., 1]
        def pdf(x):
            x = gs.reshape(gs.array(x), (-1,))
            constant = (1. / gs.sqrt(2*gs.pi*stds**2))
            return constant*gs.exp(-((x-means)**2)/(2*stds**2))
        return pdf

space = MyInformationManifold(equip=False)
space.equip_with_metric(FisherRaoMetric, support=(-10, 10))
point = gs.array([1., 1])
print(space.metric.metric_matrix(point))

I am probably doing something wrong in a very stupid way, but I can’t figure it out apparently.

Thanks in advance.

Regards
francis

**Comment by luisfpereira** [comment]
Dear @ftuerlinckx, sorry my late reply. I'm very glad to know geomstats will be of use in your project.

The problem seems to be on the installation.  Are you sure you are using the python installation where you install geomstas via `pip install git+https://github.com/geomstats/geomstats.git@main#egg=geomstats`? I've followed the steps I told you and it works.

Please let me know if this helps somehow.
