### ISSUE TITLE
Use ruff for linting in the CI

### ISSUE THREAD

**Issue by luisfpereira** [geomstats/geomstats#1927]
[ruff](https://github.com/astral-sh/ruff) is definitely faster than `flake8` (see repo README) and supports "Drop-in parity with [Flake8](https://docs.astral.sh/ruff/faq/#how-does-ruff-compare-to-flake8), isort, and Black".

I think we should replace them in our CI and update pre-commit to be based on `ruff`.

NB: it is already used in some libraries in our ecosystem (e.g. [SciPy](https://github.com/scipy/scipy)).

Green light here, @ninamiolane? (I'm thinking about also using it in [neurometry](https://github.com/geometric-intelligence/neurometry).)

**Comment by ninamiolane** [comment]
@luisfpereira should we use the opportunity to also remove deep source ? I feel that we do not use it as much, so it's mostly making the unit tests process more cumbersome.
