### ISSUE TITLE
On the creation of empty quotient metrics

### ISSUE THREAD

**Issue by luisfpereira** [geomstats/geomstats#1931]
This issue intends to discuss the need (and reason) for creating empty quotient metrics. It is motivated by `discrete_curves`, but I think it will apply in other cases, such as pullback metrics.

For this particular case see: `SRVReparametrizationQuotientMetric`, `SRVRotationQuotientMetric`, `SRVRotationReparametrizationQuotientMetric`.

What I suggest is that, since these metrics are empty, we delete the metric and simply use `QuotientMetric`. This is possible as the metric is fully defined by the fiber bundle.
In the cases we need to override some method, then we create a corresponding metric.
From a user perspective, this has zero impact, as a user create theses spaces using  `.equip_with_quotient_structure`.
Notice tests can still be done for all these combinations and it is easy to keep track of all the possibilities through the mapping in `DiscreteCurvesStartingAtOrigin`.

This prevents an explosion on the number of objects in the library, with names that are longer and longer, and harder to come up with.

What is your opinion, @alebrigant and @ninamiolane? If we agree, I'll implement it immediately.

**Comment by alebrigant** [comment]
I completely agree with this suggestion: if there is a way of removing these empty classes without changing the user experience and in a way that still allows tests then it's an important improvement !
