### ISSUE TITLE
Bug: Examples provided in documentation do no work

### ISSUE THREAD

**Issue by isacostamaia** [geomstats/geomstats#1937]
### Describe the bug

Some examples provided in documentation do not work.
I got errors in some classes calls:

- ` 'RiemannianKMeans' object has no attribute 'cluster_centers_'` from plot_kmeans_clusters.py

- `OnlineKMeans.__init__() got an unexpected keyword argument 'metric'`  from [https://geomstats.github.io/getting_started/first-steps.html](this example)

### Steps/Code to Reproduce

run plot_kmeans_clusters.py
and 
[https://geomstats.github.io/getting_started/first-steps.html](this example)

### Expected Behaviour

Running RiemannianKMeans and OnlineKMeans classes

### Actual Behaviour

` 'RiemannianKMeans' object has no attribute 'cluster_centers_'`
`OnlineKMeans.__init__() got an unexpected keyword argument 'metric'` 

### Your environment

```shell
geomstats==2.7.0
ubuntu
```

**Comment by luisfpereira** [comment]
Thanks for opening the issue @isacostamaia. This is just a matter of version: online documentation follows `main` branch, not the version available in `pypi` (we should probably provide different versions for the documentation at some point). Please install `geomstats` from the `main` branch and it will work (we are testing all the notebooks).
