### ISSUE TITLE
Bug: Import Failure on Python 3.12

### ISSUE THREAD

**Issue by KulikDM** [geomstats/geomstats#1951]
### Describe the bug

I was testing Geomstats on python 3.12 and got the following error. Not sure if full support has been added for python 3.12 yet but see that no bug issue has been raised for this. 

### Steps/Code to Reproduce

```
from geomstats.geometry.euclidean import Euclidean
```

### Expected Behaviour

Example: No error is thrown

### Actual Behaviour

```
from geomstats.geometry.euclidean import Euclidean
/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/geomstats/geometry/euclidean.py:3: in <module>
    import geomstats.backend as gs
/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/geomstats/__init__.py:7: in <module>
    import geomstats.geometry.discrete_curves
/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/geomstats/geometry/discrete_curves.py:11: in <module>
    import geomstats.backend as gs
E   ModuleNotFoundError: No module named 'geomstats.backend'
```

### Your environment

```shell
Geomstats==2.7.0
Python 3.12
OS: Windows, Ubuntu, & MacOS
```

**Comment by KulikDM** [comment]
@luisfpereira any updates on this issue?

**Comment by luisfpereira** [comment]
Thanks for pinging me, @KulikDM. I'll make this a priority.

**Comment by luisfpereira** [comment]
@KulikDM, this is now solved. Notice we haven't yet fully tested with Python 3.12 (workflow runs 3.11).
Since this is now fixed, we are probably moving the tests to 3.12 soon though.

**Comment by KulikDM** [comment]
Hi @luisfpereira, thanks so much for the speedy fix.
I ran some tests now and its working well for python 3.12 across all operating systems. However, the change also seems to have broken it for python 3.10 and all lower versions across all operating systems with the error message:
```
from geomstats.geometry.euclidean import Euclidean
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/geomstats/geometry/euclidean.py:5: in <module>
    import geomstats.backend as gs
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/geomstats/__init__.py:7: in <module>
    import geomstats.geometry.discrete_curves
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/geomstats/geometry/discrete_curves.py:14: in <module>
    from geomstats.geometry.euclidean import Euclidean
E   ImportError: cannot import name 'Euclidean' from partially initialized module 'geomstats.geometry.euclidean' (most likely due to a circular import) (/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/geomstats/geometry/euclidean.py)
```
Sorry for the bad news, but hope it helps.

**Comment by luisfpereira** [comment]
Thank you very much @KulikDM! I'm on it.

**Comment by luisfpereira** [comment]
@KulikDM, after #2008 I can run geomstats in 3.9-3.12. These [tests](https://github.com/geomstats/geomstats/actions/runs/9496676328/job/26171604043) also seem to suggest things at least run. Could you please check if the issue persists?

**Comment by KulikDM** [comment]
Hi @luisfpereira, well done! Just reran the tests and everything is passing. You're star. Looking forward to the next geomstats release!
