### ISSUE TITLE
Bug: Why is the result not an antisymmetric matrix?

### ISSUE THREAD

**Issue by pyni** [geomstats/geomstats#1966]
### Describe the bug

Hello, here is my problem.
When I run:
from scipy.spatial.transform import Rotation as R
import numpy as np
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
SO3_GROUP = SpecialOrthogonal(n=3, point_type="matrix")
SO3_GROUP.metric.log(point=R.from_rotvec( np.array([-0.10889328,-0.59982776,-1.72682313]) ).as_matrix() ) 
it shows:
array([[ 0.        ,  1.72682313, -0.59982776],
       [-1.72682313,  0.        ,  0.10889328],
       [ 0.59982776, -0.10889328,  0.        ]])
This result is good.

But when I run :
from scipy.spatial.transform import Rotation as R
import numpy as np
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
SO3_GROUP = SpecialOrthogonal(n=3, point_type="matrix")
SO3_GROUP.metric.log(point=R.from_rotvec( np.array([-0.10889328,-0.59982776,-1.72682313]) ).as_matrix() ,base_point=R.from_rotvec( np.array([-0.47649147,-0.14339756, 0.39216581]) ).as_matrix())

it show the result is :
array([[ 0.71461135,  1.99494164, -0.04802872],
       [-1.75494873,  0.86416226, -0.00947264],
       [ 1.07021347,  0.08444864, -0.0077416 ]])

And This matrix is strange, which is not a antisymmetric matrix. So how can I get its Vee operation?

### Steps/Code to Reproduce

from scipy.spatial.transform import Rotation as R
import numpy as np
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
SO3_GROUP = SpecialOrthogonal(n=3, point_type="matrix")
SO3_GROUP.metric.log(point=R.from_rotvec( np.array([-0.10889328,-0.59982776,-1.72682313]) ).as_matrix()  )

from scipy.spatial.transform import Rotation as R
import numpy as np
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
SO3_GROUP = SpecialOrthogonal(n=3, point_type="matrix")
SO3_GROUP.metric.log(point=R.from_rotvec( np.array([-0.10889328,-0.59982776,-1.72682313]) ).as_matrix() ,base_point=R.from_rotvec( np.array([-0.47649147,-0.14339756, 0.39216581]) ).as_matrix())

### Expected Behaviour

no

### Actual Behaviour

no

### Your environment

```shell
python3
```

**Comment by johnharveymath** [comment]
Hi @pyni - thanks for reporting this. This seems to be the expected behaviour to me.

To clarify, the output of `SO3_GROUP.metric.log(point, base_point)` is a tangent vector at `base_point`. You can confirm this by running 
```
vec = SO3_GROUP.metric.log(point, base_point)
SO3_GROUP.is_tangent(vec, base_point)
```
This should always return `True`. 

The reason that `vec` is not antisymmetric is that it is only tangent vectors to the identity that are antisymmetric. This is why your first output was antisymmetric (you did not specify `base_point` so it defaulted to the identity) but your second output is not (you specified a `base_point` that was not the identity).

**Comment by pyni** [comment]
@johnharveymath 
Hi, thanks for your reply,I try to read your code, but i can hardly understand why you should  compute a left-invariant vector field bringing base_point to point in log algorithm:
        logm = gs.linalg.logm
        if base_point is None:
            return logm(point)
        lie_algebra_vec = logm(cls.compose(cls.inverse(base_point), point))
        return cls.compose(base_point, lie_algebra_vec) # Actually,  i do not know why it requires this step?

do you have any reference?Thanks.
