### ISSUE TITLE
Bug: invalid syntax error during pytest

### ISSUE THREAD

**Issue by ahenkes1** [geomstats/geomstats#1999]
### Describe the bug

I encounter an `SyntaxError: invalid syntax` during execution of the tests. 

### Steps/Code to Reproduce

I cloned the repo and installed it using pip with the [all] flag. I am using Python3.10, which, follwing the pyproject.toml, should be supported. I have the strong feeling that the syntax error is related to the python version and the asterix operator (*) for unpacking, as the error points to that. In that case, there should be a version check during install.

### Expected Behaviour

The tests should run.

### Actual Behaviour

More specifically, the following error occurs:

`ImportError while loading conftest '/home/ah/Codes/geomstats/tests/conftest.py'.
tests/conftest.py:1: in <module>
    from geomstats.test.conf import (
geomstats/__init__.py:7: in <module>
    import geomstats.geometry.discrete_curves
geomstats/geometry/discrete_curves.py:14: in <module>
    from geomstats.geometry.euclidean import Euclidean
geomstats/geometry/euclidean.py:6: in <module>
    from geomstats.geometry.base import VectorSpace
geomstats/geometry/base.py:12: in <module>
    from geomstats.geometry.pullback_metric import PullbackMetric
geomstats/geometry/pullback_metric.py:8: in <module>
    from geomstats.numerics.geodesic import ExpODESolver, LogShootingSolver
E     File "/home/ah/Codes/geomstats/geomstats/numerics/geodesic.py", line 176
E       return y[..., 0, *slc]
E                        ^
E   SyntaxError: invalid syntax`

### Your environment

```shell
Geomstats main branch https://github.com/geomstats/geomstats/commit/929c0b1fd731e4d4c0b94223820920fd6d6f9c63

Linux TUXEDO OS 3 (release 22.04) -> this is a kind of Ubuntu fork, should not matter.
```

**Comment by luisfpereira** [comment]
@ahenkes1, the problem is the use of `*slc`, which only works from python 3.11+ (my bad).
Is upgrading python version an issue for you?

In any case, I'll make the code compatible with 3.10.

**Comment by ahenkes1** [comment]
Thank you very much!
