### ISSUE TITLE
About jacobian_translation function

### ISSUE THREAD

**Issue by pyni** [geomstats/geomstats#2021]
### Describe the bug

Hi, May I know do you have any reference for jacobian_translation() function in
https://github.com/geomstats/geomstats/blob/916adf1d9f802ad6647716c96dd3937d84e17ddd/geomstats/geometry/special_orthogonal.py#L1493
I can hardly undertand what's going on for this function.

And I try the codes:

import geomstats.backend as gs
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
from scipy.spatial.transform import Rotation as R
import numpy as np 
SO3_GROUP = SpecialOrthogonal(n=3, point_type="vector")
point = gs.array([0.1, 0.2, 0.3]) 
base_point = gs.array([0.4, 0.5, 0.6])
 
log_result = SO3_GROUP.metric.log(point, base_point) 
print('vec ',log_result  )
  
SO3_GROUP_mat = SpecialOrthogonal(n=3, point_type="matrix")
 
point_mat=R.from_rotvec( point).as_matrix() 
base_point_mat=R.from_rotvec( base_point ).as_matrix() 
log_result_mat = SO3_GROUP_mat.metric.log(point_mat, base_point_mat) 
print('mat',log_result_mat )

I know log_result and log_result_mat are the same result, but I do not know how can I transfer log_result_mat to log_result?   It seems log_result_mat is not skew-symmetric matrix. I do not know how to do the Vee operation for it.

### Steps/Code to Reproduce

import geomstats.backend as gs
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
from scipy.spatial.transform import Rotation as R
import numpy as np 
SO3_GROUP = SpecialOrthogonal(n=3, point_type="vector")
point = gs.array([0.1, 0.2, 0.3]) 
base_point = gs.array([0.4, 0.5, 0.6])
 
log_result = SO3_GROUP.metric.log(point, base_point) 
print('vec ',log_result  )
  
SO3_GROUP_mat = SpecialOrthogonal(n=3, point_type="matrix")
 
point_mat=R.from_rotvec( point).as_matrix() 
base_point_mat=R.from_rotvec( base_point ).as_matrix() 
log_result_mat = SO3_GROUP_mat.metric.log(point_mat, base_point_mat) 
print('mat',log_result_mat )

### Expected Behaviour

how can I transfer log_result_mat to log_result?   It seems log_result_mat is not skew-symmetric matrix. I do not know how to do the Vee operation for it.

### Actual Behaviour

N.A.

### Your environment

```shell
PYTHON
```

**Comment by dherrera1911** [comment]
The `log_result_mat` in your code should not be skew symmetric.

The tangent space at point $R \in SO(3)$ is given by $RX$ where $X$ is skew symmetric. The tangent space at the identity is given by skew symmetric matrices, but this is not true in general.

You can see this by multiplying your `log_result_mat` by $R^{-1}$, using `gs.linalg.inv(base_point_mat) @ log_result_mat`, which does return a skew symmetric matrix.

I'm not sure how to convert from the `log_result_mat` to `log_result` you mention, which are the tangent vectors of the manifold using  matrix and vector representations, but to me this seems unrelated to your initial question about `jacobian_translation`.
