### ISSUE TITLE
Error in executing geomstats samples

### ISSUE THREAD

**Issue by rezagodaz** [geomstats/geomstats#211]
@ninamiolane 

I am trying to use the tool "geomstats". I tried to install it, so I installed Ubuntu 18.04 and all of the tools introduced in the readme files of geomstats exactly. After that I try to execute: 1) nose2, run.sh ( from geomstats-master folder ), and  2) mnist_hypersphere.py ( from deep_learning folder ). 
for the first runn I get this error:

> KeyError: 'GEOMSTATS_BACKEND'
> ----------------------------------------------------------------------
> Ran 27 tests in 0.435s
> FAILED (errors=19)
> 
and for the second execution I get this:

> Using TensorFlow backend.
> Using tensorflow backend
> x_train shape: (60000, 28, 28, 1)
> 60000 train samples
> 10000 test samples
> Traceback (most recent call last):
>   File "mnist_hypersphere.py", line 54, in <module>
>     kernel_manifold=Hypersphere(hypersphere_dimension)))
>   File "/usr/local/lib/python3.6/dist-packages/Keras-2.1.6-py3.6.egg/keras/legacy/interfaces.py", line 91, in wrapper
>   File "/usr/local/lib/python3.6/dist-packages/Keras-2.1.6-py3.6.egg/keras/layers/convolutional.py", line 465, in __init__
>   File "/usr/local/lib/python3.6/dist-packages/Keras-2.1.6-py3.6.egg/keras/layers/convolutional.py", line 104, in __init__
>   File "/usr/local/lib/python3.6/dist-packages/Keras-2.1.6-py3.6.egg/keras/engine/base_layer.py", line 122, in __init__
> TypeError: ('Keyword argument not understood:', 'kernel_manifold')
> 

My settings are:

UBUNU 18.04
tensorflow==1.8
python==3.6.7
keras==2.1.6 installed from kerass folder of the tool applications-master and uses tf_patch
autograd
codecov
coverage
h5py==2.8.0
matplotlib
nose2
numpy==1.16.3
scipy
torch==0.4.0

 Please help me install it correctly.

**Comment by ninamiolane** [comment]
you need to define the backend, from the command line:
```
export GEOMSTATS_BACKEND=numpy
```
or
```
export GEOMSTATS_BACKEND=tensorflow
```
if you wish to use tensorflow.

The example `mnist` might not work with the latest version of geomstats. If you are still interested, you should probably use the version 1.7.

I'm closing this, but feel free to re-open if you are still interested.
