### ISSUE TITLE
Implement Procrustes metric on SPD matrices

### ISSUE THREAD

**Issue by ythanwerdas** [geomstats/geomstats#244]
For now, the Riemannian metric implemented on SPD matrices in geomstats is the so called affine-invariant metric or Fisher-Rao metric. The Procrustes metric is another canonical Riemannian metric on SPD matrices. It can also be viewed as coming from the theory of optimal transport and it is also called the Bures-Wasserstein metric.

Implementing the Procrustes metric is a first step towards defining families of Riemannian metrics on SPD matrices such as the alpha-Procrustes metrics, the power-affine metrics, etc.

**Comment by stefanheyder** [comment]
@ythanwerdas this was fixed by #263 right?

**Comment by ythanwerdas** [comment]
Not entirely :)

**Comment by nguigs** [comment]
Fixed by #889
