### ISSUE TITLE
invariant metric with point_type=matrix

### ISSUE THREAD

**Issue by nguigs** [geomstats/geomstats#245]
The log seems to expect vectors even when using matrices to represent points
```
SO3_GROUP = SpecialOrthogonalGroup(n=3, point_type='matrix')
METRIC = SO3_GROUP.bi_invariant_metric

N_SAMPLES = 10

data = SO3_GROUP.random_uniform(n_samples=N_SAMPLES)
mean = METRIC.mean(data)
```
This raises a ValueError, due to
https://github.com/geomstats/geomstats/blob/e786bd606532cce887acf5d4d7adf5630f8b241f/geomstats/geometry/invariant_metric.py#L291

which can be removed as n_points is not used later, but then
https://github.com/geomstats/geomstats/blob/e786bd606532cce887acf5d4d7adf5630f8b241f/geomstats/geometry/invariant_metric.py#L260

Is it necessary?

**Comment by nguigs** [comment]
In fact rotation_vector_from_matrix should be used as the log in that case

**Comment by stefanheyder** [comment]
So if I remember correctly, the Riemannian `exp` and `log` for left/right invariant metrics should coincide with the Lie group `exp` and `log` (from the left/right). Shouldn't we then just call `group.log(....)` in the `invariant_metric.left_exp_from_identity` (and related functions)?

**Comment by stefanheyder** [comment]
Also should we add `point_type` as an argument to the methods in the class?

**Comment by nguigs** [comment]
> So if I remember correctly, the Riemannian `exp` and `log` for left/right invariant metrics should coincide with the Lie group `exp` and `log`
That's not true if the metric is not bi-invariant I think, e.g. on SE(n): group `exp` is the matrix `exp` while the left inv. Riemannian `exp` is: `exp(\Omega), tv`. See https://en.wikipedia.org/wiki/Exponential_map_(Riemannian_geometry)#Relationships_to_exponential_maps_in_Lie_theory

**Comment by nguigs** [comment]
This is outdated, the following now works:

```python
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
from geomstats.learning.frechet_mean import FrechetMean
SO3_GROUP = SpecialOrthogonal(n=3, point_type='matrix')
METRIC = SO3_GROUP.bi_invariant_metric

N_SAMPLES = 10

data = SO3_GROUP.random_uniform(n_samples=N_SAMPLES)
estimator = FrechetMean(METRIC).fit(data)
mean = estimator.estimate_
```
