### ISSUE TITLE
Refactor Common Matrix Operations

### ISSUE THREAD

**Issue by stefanheyder** [geomstats/geomstats#277]
Vectorized matrix operations such as multiplication, commutator and comarpison with a tolerance should be added to the MatrixSpace class and refactored from old code.

**Comment by ninamiolane** [comment]
Agreed! 🎉 (As soon as it does not lead us to rewrite `numpy`, or unnecessarily wrap it.)

**Comment by nguigs** [comment]
Done in #388.
