### ISSUE TITLE
Write Installation guide

### ISSUE THREAD

**Issue by stefanheyder** [geomstats/geomstats#278]
Currently there are some problems installing geomstats under different Python versions, in particular Python 3.7 and 3.8 cause problems with tensorflow and pytorch.

To make installation more consistent this, a working installation method should be documented, including the required programs (pyenv / pipenv (?)) and operations required to install all dependecies without causing any error.

**Comment by ninamiolane** [comment]
Now `requirements.txt` contains a working installation method, for python versions 3.5, 3.6, 3.7 and 3.8.
