### ISSUE TITLE
Add a dataset directory

### ISSUE THREAD

**Issue by stefanheyder** [geomstats/geomstats#302]
This should contain common datasets of Riemannian Geometry, see e.g. https://cran.r-project.org/web/packages/circular/circular.pdf and https://cran.r-project.org/web/packages/CircNNTSR/CircNNTSR.pdf for classical datasets available in R (related to circular / spherical statistics).

**Comment by ninamiolane** [comment]
On which platform should we store the datasets? They cannot be on github for memory reasons.

Maybe OSF? https://osf.io/
Or a platform that scikit-learn / pytorch / tf / keras are using?

**Comment by stefanheyder** [comment]
Good idea, but I am afraid that I am not familiar with publishing datasets.

Also does someone know how licensing works for datasets, especially if we want to reuse some datasets from e.g. R packages?

**Comment by ninamiolane** [comment]
For starters, we could actually follow scikit-learn strategy and create a directory for small datasets directly on github:
https://github.com/scikit-learn/scikit-learn/tree/master/sklearn/datasets

Not sure how licensing works there though.

**Comment by ninamiolane** [comment]
A repository for small datasets has been created here: https://github.com/geomstats/geomstats/tree/master/examples/data.

**Comment by nguigs** [comment]
This was done in #780 or before.
