### ISSUE TITLE
Unify backend interface

### ISSUE THREAD

**Issue by stefanheyder** [geomstats/geomstats#303]
Some functions do not behave the same in different backends. One example is `gs.diag`:

If numpy is selected as a backend the following call results in a 3-dimensional array: `gs.diag(gs.array([1., 1., 0.]))` will have shape `(1, 3, 3)`. Calling the same code with pytorch as backend results in a tensor of shape `(3,3)`.

To resolve this, we should specify (and unify) the output shapes of backend arrays.

**Comment by opeltre** [comment]
listed some implementation issues #304

**Comment by opeltre** [comment]
On numpy `gs.eye(3, 3, 1)` yields a 3x3 matrix with ones on the upper diagonal/
On pytorch `gs.eye(3, 3, 1)` fails because `gs.eye` expects 1 to 2 arguments. (expects `[3, 3, 1]`?)

**Comment by opeltre** [comment]
also `gs.diag`'s shape signature is inconsistent

**Comment by opeltre** [comment]
As mentioned in issue 304 problems with:
+ `expm`
+ `logm`
+ `vectorize`

Thanks to @ythanwerdas `expm` and `logm` should now work and vectorize correctly on numpy :)
They do not on pytorch and there's no `vectorize` which could be useful to fix vectorization issues/performance at a single place in the future

**Comment by stefanheyder** [comment]
I compiled a list of all functions that are currently available in the backends (some are only implemented in a single backend ...) just so we can keep track here what to keep and what to remove. This is just for the `__init__.py` files:
```python
# Numpy
abs
all
allclose
amax
amin
any
append
arange
arccos
arccosh
arcsin
arctan2
arctanh
argmax
argmin
array
asarray
average
boolean_mask
byte_to_float
cast
cast_to_complex
clip
concatenate
cond
copy
cos
cosh
cov
cross
cumprod
diag
diagonal
divide
dot
ehile_loop
einsum
empty
empty_like
equal
eval
exp
expand_dims
eye
flip
float_to_double
floor
gather
get_mask_i_float
greater
greater_equal
hsplit
hstack
identity
indexing
isclose
ix_
less
less_equal
linspace
log
logical_or
matmul
maximum
mean
mod
ndim
nonzero
norm
normal
ones
ones_like
outer
prod
rand
randint
real
repeat
reshape
shape
sign
sin
sinh
sqrt
squeeze
stack
sum
tan
tanh
tile
to_ndarray
trace
transpose
triu_indices
vectorize
vstack
where
zeros
zeros_like
# PyTorch
clamp
eq
gt
seed
T
# Tensorflow
unstack
while_loop
```
Here are the functions appearing in the `linalg.py` files, here numpy has all the functions, but pytorch and tensorflow do not implement some that numpy does.
```python
# Numpy: Linalg
det,
eig,
eigh,
eigvalsh,
exp
expm
expsym
inv,
is_symmetric
logm
matrix_rank,
norm,
powerm
qr
sqrtm
svd
to_ndarray
# PyTorch: Linalg
# Tensorflow: Linalg
```
There is also `random.py` where all the backend implement the following functions:
```python
choice
normal
rand
randint
randn
seed
uniform
```

**Comment by stefanheyder** [comment]
Also a list of goals this refactoring should have at the end, feel free to comment / add / remove any you want!

* provide API common to all three supported backends
* unify in and output of those backends
* Test all backend implementations, by **only** testing the abstract interface
  * test functionality as well as correct vectorization behaviour (shape!)
* Find a cleaner way than the `GEOMSTATS_BACKEND` environment variable to switch between backends
* (optional) maybe provide numpy as a general package for doing computations, rather than relying on the backend interface all the time,
  * would allow for slimmer API
  * functions that are not time critical e.g. random variable creation, helper functions such as upper / lower triangle indices only make the backend more bloated and higher maintenance
  * this would mean that we have to differentiate between numpy and backend arrays (e.g. if necessary cast the np array to a backend array and vice versa) which for performance reasons should be avoided

**Comment by stefanheyder** [comment]
More info about usage of the backend, I ran `grep -hori "gs\.[a-zA-Z_\.]*" geomstats/learning geomstats/geometry | sort | uniq -c | sort -nr` to see how often each function was used, so we can get a feeling which functions are important to keep and which we can safely abandon:
```csv
    301 gs.to_ndarray
     80 gs.einsum
     75 gs.matmul
     49 gs.cast
     45 gs.transpose
     45 gs.array
     44 gs.float
     41 gs.zeros
     38 gs.tile
     31 gs.isclose
     29 gs.concatenate
     28 gs.sin
     28 gs.ndim
     24 gs.sum
     23 gs.cos
     20 gs.squeeze
     20 gs.reshape
     19 gs.zeros_like
     18 gs.sqrt
     18 gs.linalg.inv
     17 gs.linalg.norm
     17 gs.eye
     15 gs.pi
     14 gs.maximum
     13 gs.hstack
     11 gs.shape
      9 gs.where
      9 gs.random.rand
      9 gs.ones
      9 gs.all
      8 gs.repeat
      7 gs.trace
      7 gs.linalg.sqrtm
      7 gs.get_mask_i_float
      7 gs.copy
      7 gs.clip
      6 gs.linalg.powerm
      6 gs.linalg.expm
      6 gs.int
      6 gs.flip
      6 gs.dot
      6 gs.asarray
      5 gs.vstack
      5 gs.ones_like
      5 gs.gather
      5 gs.expand_dims
      5 gs.equal
      5 gs.arange
      5 gs.allclose
      4 gs.stack
      4 gs.linalg.qr
      4 gs.less_equal
      4 gs.arctan
      4 gs.arccos
      3 gs.random.normal
      3 gs.norm
      3 gs.log
      3 gs.linalg.logm
      3 gs.linalg.det
      3 gs.hsplit
      3 gs.argmin
      3 gs.abs
      2 gs.vectorize
      2 gs.triu_indices
      2 gs.tanh
      2 gs.tan
      2 gs.sinh
      2 gs.sign
      2 gs.real
      2 gs.random.randint
      2 gs.linalg.svd
      2 gs.linalg.eigvalsh
      2 gs.less
      2 gs.floor
      2 gs.exp
      2 gs.empty_like
      2 gs.divide
      2 gs.diag
      2 gs.cond
      2 gs.arcsin
      2 gs.amax
      1 gs.while_loop
      1 gs.tril_indices
      1 gs.outer
      1 gs.mean
      1 gs.logical_or
      1 gs.linalg.eigh
      1 gs.linalg.eig
      1 gs.greater
      1 gs.diagonal
      1 gs.diag_indices
      1 gs.cov
      1 gs.cosh
      1 gs.argmax
      1 gs.arctanh
      1 gs.arccosh
      1 gs.amin

```

**Comment by stefanheyder** [comment]
I noticed that we have a lot of geometric functions (`gs.sin`, `gs.cos`, `gs.arctan` etc.) present in the backend interfaces. One way I could think of implementing this (without writing a lot of wrapper functions as we are currently doing) is to use the "magic" method `__getattr__` (see e.g. https://blog.rmotr.com/python-magic-methods-and-getattr-75cf896b3f88) where we defer to the current librarys methods. Something like this:

```python
class Backend():
    ....
    def __getattr__(self, attr):
        if attr == "sin":
            return self.library.sin
        raise AttributeError("'Backend' object has no attribute '%s'" % attr)
    ....
```
where we would of course not only implement `sin`. I don't think this is best practice (as it can lead to confusing behaviour, will need some good documentation + tests), and we have to check the interfaces of functions across the three backends carefully. On the other hand it would save much time (and code) and adding functions that behave the same across all backends will be easily implemented (without blowing up the code base too much).

**Comment by opeltre** [comment]
Getting down our `301 gs.to_ndarray` score is a great challenge towards #338 fixing vectorization issues!

**Comment by nguigs** [comment]
`gs.to_ndarray` is now at 68!
The backend as been refactor in a consistent way in #543.
