### ISSUE TITLE
Matrices and Lie groups: classes and inheritance

### ISSUE THREAD

**Issue by opeltre** [geomstats/geomstats#317]
Right now the GL(n) `log` maps points to `np.linalg.logm` which is not implemented in the torch backend (then apply `np.real` to the result as the output is a complex matrix)

The GL(n) `exp` map points to `gs.expm` which is does not handle vectorization in the torch backend. 

Most (all) Lie group classes may actually inherit these methods from GL(n): SO(n), SE(n), SPD(n)... 

It seems that almost all geomstats classes may be partitioned in two, being either embedded in R^n or in M_n(R). For all those in the latter it seems quite important to have a **consensual and working matrix logarithm and exponential**

**Comment by opeltre** [comment]
I suggest using this issue thread to discuss anything related to matrices classes!

**Comment by opeltre** [comment]
The idea is to leverage on python's inheritance to limit code reuse, so that the library is:
+ more readable by anyone interested, be it reviewers, new contributors or simply ourselvesus 
+ greatly improve maintanability by limiting the code base's organic growth

**Comment by opeltre** [comment]
In the proposed draft, GL(n) implements: 
+ `identity`
+ `compose` (alias of `Matrices.mul`)
+ `exp`, using `gs.linalg.expm` but admitting a base point
+ `log`, same with `gs.linalg.logm`
+ `orbit` returns the one-parameter orbit interpolating 2 points (geodesic for the canonical metric)

**Comment by opeltre** [comment]
Then by inheritance, SO(n) simply overrides:
+ `inv` by pointing to `Matrices.transpose`

**Comment by opeltre** [comment]
As discussed with @ythanwerdas, the group of SPD(n) matrices should override:
+ `exp` by relying on symmetry, using his implementation (in the backend for the moment)
+ `log`?
for performance concerns. 

However there would be no need to rewrite `SPD.orbit` for instance, as it would simply call the class's overriden `SPD.exp` and `SPD.log`

**Comment by opeltre** [comment]
The draft is in the 'matrices' branch of my repo for now. 
I simply created duplicate files with shortened names to avoid any conflicts: 
+ [matrices](https://github.com/opeltre/geomstats/blob/matrices/geomstats/geometry/matrices.py)
+ [general linear group](https://github.com/opeltre/geomstats/blob/matrices/geomstats/geometry/general_linear.py)
+ [special orthogonal group](https://github.com/opeltre/geomstats/blob/matrices/geomstats/geometry/special_orthogonal.py)

**Comment by opeltre** [comment]
As discussed with @stefanheyder, right now the behaviour of `SO(n).exp` would be to exponentiate any matrix of `Mat(n, n)`, thus giving an element of `GL(n)` if fed a non-skew-symmetric matrix as input.

This might be problematic if the user does not really know what he is doing. 

The idea would be to eventually enforce sanity checks by piping some `SO(n).is_tangent` into `SO(n).exp`. 

None that `SO(n)` would only have to override the trivial `GL(n).is_tangent`, the change amounting to `GL.exp` calling `class.is_tangent`.

**Comment by nguigs** [comment]
> It seems that almost all geomstats classes may be partitioned in two, being either embedded in R^n or in M_n(R)**

That's the true, we should decide which classes need to inherit EmbeddedManifold and which should inherit from the matrix class in which they are embedded because both are done right now. I think in Matrix manifolds, it is more useful to inherit from `GeneralLinear` than `EmbeddedManifold`
