### ISSUE TITLE
Refactor code on product manifolds/metrics, landmarks sets, discretized curves

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#377]
Currently, the following classes are implemented:

- `ProductManifold`: 
`n_samples` of `n_points` on `n_manifolds` manifolds M_1 x...x M_n_manifolds, where M_1 x...x M_n_manifolds are potentially different manifolds.
- `Landmarks`: `n_samples` of `n_landmarks` on `n_manifolds` M x ... x M where the same manifold M is used, but the number of landmarks may vary.
- `DiscretizedCurves`: `n_samples` of curves on a manifold M, where a curve is a set of landmarks which are called `sampling_points` in this class. The number of landmarks/sampling_points may vary.

With associated `ProductMetric`, `L2Metric`, etc.

There seem to be methods of `Landmarks`/`DiscretizedCurves` that can be refactorized into `ProductManifold`, and methods of` L2Metric` that can be refactorized into `ProductMetric`.

Notes:
- We should agree on the point representation for these spaces, depending on the cases:
    - either [n_samples, dim1 + .. + dim2]
    - or [n_samples, n_landmarks, dim]?
- We could fix the number of landmarks n_landmarks in the class `Landmarks`, and n_sampling_points in the class `DiscretizedCurves`? Methods that do not depend on the number of landmarks / sampling_points could be @classmethod. Alternatively, we could use `ProductManifold` each time n_landmarks is fixed and `Landmarks` each time we need a flexible number of landmarks (for example to study asymptotic when the number of landmarks goes to infinity, without having to instantiate an infinite number of `Landmarks` objects).

**Comment by ninamiolane** [comment]
@YannCabanes you could be interested in this discussion.

**Comment by nguigs** [comment]
I think `n_landmarks` should be the same for all samples in `LandmarkSpace` (and in theory should correspond to the same feature in e.g. an image) but could vary in `DiscretizedCurves`. Thus [n_samples, n_landmarks, dim] is adapted to `Landmarks` but not to `DiscretizedCruves`.

**Comment by nguigs** [comment]
Landmarks uses ProductManifold while it is not necessary that DiscreteCurve does.
