### ISSUE TITLE
Resolve outstanding docstring issues

### ISSUE THREAD

**Issue by cshewmake2** [geomstats/geomstats#398]
Christian Shewmake
January 23, 2020

**Hello geomstats wranglers!**

Thanks for your patience while I was putting together v1 of the API documentation. I think the GeomStats API reference page is going to be totally awesome using these new tools/standards. However, there’s quite a lot of work remaining before we can take it live.

**First, let’s restrict our attention to the geometry section.**
There are a couple of design decisions to make which should be discussed:
1. _Succinct vs Verbose Docstrings_
    1. How do we want to handle small, simple functions?
		-> It’s painful to annotate Descriptions, Parameters, and Returns for these functions.

2. _Singular or Plural Input Language_
    1. How do we want to handle docstrings for vectorized operations?
		-> I vote singular language.
		-> How do we annotate whether or not something supports vectorization?

**Next, there are outstanding issues in each of the files related to:**

3. _Absent or Unclear descriptions and parameter types_
    1. Some summaries and descriptions aren’t very useful / descriptive.
    2. Many ‘Parameters’ and ‘Returns’ entries lack type annotations

4. _Inconsistent Referencing_
    1. Some docstrings have weblinks which could potentially expire over the lifetime of the project
    2. Some docstrings don’t use a references section
		-> We need citations in the format you’d use in a paper (accompanied by links to paper pdfs would be nice)

5. _Inconsistent Math Formatting_
    1. Some docstrings use LaTeX inline or in sections via “:math:`eqn`” or “.. math:: eqn”, respectively.
    2. Some docstrings don’t use these options at all
    3. Some docstrings use the ‘math’ directives but have syntax errors (from rst or LaTeX or both) and don’t render properly.
--------
**Given that there are so many files to address, I think we should divide them up, resolve the issues, then merge them in piece-by-piece.** 
I’ve gone through some of these fixes myself, so I am happy to answer any and all questions related to syntax and our internal ‘style guide’. We can also discuss items for which you’re unsure once you raise a PR; I would be happy to review and give prompt feedback on these.

**Comment by opeltre** [comment]
Could you edit the post with a link to the documentation web page? :)

**Comment by ninamiolane** [comment]
From @nguigs : 
"We should divide files to each look at. I will take care of
connection
riemannian_metric
landmarks_space
"

**Comment by stefanheyder** [comment]
I will take care of 

```
geometry/lie_algebra.py
geometry/lie_group.py
geometry/special_euclidean.py
geometry/speical_orthogonal.py
geometry/skew_symmetric_matrices.py
```

**Comment by stefanheyder** [comment]
Also here is a list of files so we tick them of so we see our documentation progress :)

- [ ] __init__.py
- [ ] connection.py
- [ ] discretized_curves.py
- [ ] embedded_manifold.py
- [ ] euclidean.py
- [ ] general_linear.py
- [ ] grassmannian.py
- [ ] hyperbolic.py
- [ ] hypersphere.py
- [ ] invariant_metric.py
- [ ] landmarks.py
- [ ] lie_algebra.py
- [ ] lie_group.py
- [ ] manifold.py
- [ ] matrices.py
- [ ] minkowski.py
- [ ] poincare_polydisk.py
- [ ] product_manifold.py
- [ ] product_riemannian_metric.py
- [ ] riemannian_metric.py
- [ ] skew_symmetric_matrices.py
- [ ] spd_matrices.py
- [ ] special_euclidean.py
- [ ] special_orthogonal.py
- [ ] stiefel.py

**Comment by ninamiolane** [comment]
I will take care of:
embedded_manifold
hypersphere
hyperbolic
product_manifold
product_riemannian_metric
stiefel

**Comment by cshewmake2** [comment]
Here's an example where we need to make a decision: `geomstats/geometry/product_manifold.py`

The input is the singular noun `point`, yet the output is the plural verb `regularize_points`.
**First**, I think we want the noun form `regularized_points` so people know this is a point, not a function, from the name. (Perhaps this is just an unintentional language mistake--if so, forgive me for being a jerk).

**Second**, we should use consistent naming here: 
    point & regularized_point 
    OR
    points & regularized_points

So, if operations are vectorized, should we use singular or plural nouns?

![image](https://user-images.githubusercontent.com/11378439/74051423-8a777880-499d-11ea-9936-9131e53bbd39.png)

**Comment by ninamiolane** [comment]
Agreed for the noun form!

I would prefer singular, even if it's vectorized. It is also the form that is the most present in the current code base.
