### ISSUE TITLE
Re-use exponential map in parallel transport of the HypersphereMetric

### ISSUE THREAD

**Issue by nkoep** [geomstats/geomstats#400]
The `parallel_transport` method of the `HypersphereMetric` currently re-implements the exponential map rather than using the implementation already provided in the `exp` method.

**Comment by nguigs** [comment]
The formula is similar but doesn't reimplement the exponential per se:
The way to use the exp map would be to replace https://github.com/geomstats/geomstats/blob/53b6c47e35afef372d49f9693998e3f1d3545fc9/geomstats/geometry/hypersphere.py#L546-L548
by something like (einsum omitted)
`transported = gs.dot(exp(tan_b, base_point), base_point) * normalized_b - gs.dot(exp(tan_b, base_point), normalized_b) * base_point + p_orth`
which isn't simpler than what is done so far, is it?
