### ISSUE TITLE
Uniformize float32 and float64 types across backends

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#406]
Currently, np backend mostly uses float64 while tf backend mostly uses float32, which leads to precision differences in computations.

We should add an option so that the user can choose their preferred precision, regardless of the backend.

**Comment by stefanheyder** [comment]
If we add way to configure this, we should also handle the `GEOMSTATS_BACKEND` option therein.

**Comment by ninamiolane** [comment]
Duplicate of issue #324.
