### ISSUE TITLE
Rename `random_uniform` for Euclidean and SpecialEuclidean spaces

### ISSUE THREAD

**Issue by stefanheyder** [geomstats/geomstats#407]
The names of these methods are misleading, as you cannot sample uniform from Euclidean space. As this will affect more than one space (also: non-compact Riemannian manifolds) and we should have a uniform (pun intended) handling of this, let's discuss how to handle this.

**Comment by nguigs** [comment]
I see two solutions:
- Give more details in the docstring: uniform in Euclidean space is actually uniform on [0,1]^dim and can be scaled by the parameter `bound`, in other non-compact it is uniform on a ball of a tangent space (identity for SPDs)
- Or we use a Gaussian distribution (or wrapped Gaussian) when the manifold is non compact

**Comment by ninamiolane** [comment]
(love the pun @stefanheyder !)

Let's do both recommendations from @nguigs ?
- solution 1, as per the function `random_uniform`.
- implement (wrapped) Gaussian distribution, and call it `random_gaussian`?

**Comment by nguigs** [comment]
In fact the notion of probability distribution depends on the Riemannian metric (because the volume form does). We should keep a `random_point` because it's handy, but should `random_unfirom`, `random_gaussian` (upcoming) be in the metric class @ninamiolane ?
