### ISSUE TITLE
the SPD case

### ISSUE THREAD

**Issue by opeltre** [geomstats/geomstats#413]
Creating this issue to discuss anything SPD-related!

1. So as we agreed SPD(n) should not inherit from GL(n) as it is not a subgroup of the latter. 
It is however a Lie group, so should it not share a common interface, i.e. expose methods like `compose`, `exp`, `inv`, `log` ?

    From what I understand this would be consistent with having the log-euclidean metric by default, `exp` and `log` would coincide with matrix exp and log only with `base_point = 1` while `inv` always coincides with matrix inverse. (More generally, the group operations of SPD(n) and GL(n) coincide on any commutative subgroup of GL(n), while SPD(n) is commutative)

2. Metric methods need to be properly vectorized, as they have output of type `[matrix] = [[[float]]]`. It would be nice to remove as may calls to `gs.to_ndarray` as possible from the spd file as IMO they only move the problem from a source that has yet to be identified. This should also make the code more readable. 

Help @ythanwerdas ! ;)

**Comment by nguigs** [comment]
dealt by in #1006
