### ISSUE TITLE
Tensorflow matrix square root method

### ISSUE THREAD

**Issue by nguigs** [geomstats/geomstats#427]
https://github.com/geomstats/geomstats/blob/c4e6d959db7b1bcc99b00b535b8aa5d832b62e28/geomstats/backend/tensorflow/linalg.py#L8-L19

The current implementation returns nan (in e.g. test_spd.test_parallel_transport_affine_invariant). Why don't we use [tf.linalg.sqrtm](https://www.tensorflow.org/api_docs/python/tf/linalg/sqrtm), at least for spd matrices?

**Comment by ninamiolane** [comment]
Good question. @ythanwerdas any idea why this is/should be here? Seems like a good idea to use tf.linalg.sqrtm instead!
