### ISSUE TITLE
Uniform handling of logging / warnings

### ISSUE THREAD

**Issue by stefanheyder** [geomstats/geomstats#429]
Currently we are using different mechanisms to notify the user of logging information (such as convergence warnings, which backend is in use etc.).

1. `print` https://github.com/geomstats/geomstats/blob/c4e6d959db7b1bcc99b00b535b8aa5d832b62e28/geomstats/backend/__init__.py#L19
2. `logging` https://github.com/geomstats/geomstats/blob/c4e6d959db7b1bcc99b00b535b8aa5d832b62e28/geomstats/geometry/hyperbolic.py#L129
3. `warning`https://github.com/geomstats/geomstats/blob/c4e6d959db7b1bcc99b00b535b8aa5d832b62e28/geomstats/geometry/riemannian_metric.py#L511

I think we should unify this, and after a quick research the accepted way seems to be to use the `logging` module everywhere (of course, `print` is bad coding style). After we decide which of the above options to use, we should also append best practices to our contributing file.

**Comment by ninamiolane** [comment]
Agreed to uniformize!  @est271 do you have any ideas/comments on this?

**Comment by est271** [comment]
@stefanheyder , @ninamiolane 

Yes, using the logging module is the best option. 

I used the warnings module in one of my commits because I wanted a warning to print only once during testing and using logging would have printed the warning multiple times. 

But this issue has since been fixed so changing `warnings.warn()` to `logging.warning()` will work just fine. We would just have to keep an eye out if a similar issue appears in another part of the code.

**Comment by est271** [comment]
Quick question regarding the appearance of statements before I go any further.

Using the default root logging setup, the default message format will display the levelname, the word root which is the default logger, and finally the message that is passed by using `logging.info()` or `logging.warning()`. A sample of how it will appear on the console is shown below (some info omitted for clarity).

![default](https://user-images.githubusercontent.com/56150991/74997960-43ad6800-540c-11ea-87c1-ff36104de30f.png)

I think removing the root part and just having the levelname followed by the message will be sufficient but I could leave it as is. [Other attributes can be added or taken out as well](https://docs.python.org/3/library/logging.html#logrecord-attributes) . Any suggestions about the format?

**Comment by ninamiolane** [comment]
Agreed, let's just keep the levelname and not the word root! I looked at the other attributes on your weblink, and I don't see a need for printing others. But happy to know if you have suggestions / if you have seen other attributes printed in other libraries and the advantages of it!

Thanks for looking at this!

**Comment by nkoep** [comment]
I think using the warnings module for unit tests is acceptable for the purposes of issuing a warning only once as mentioned by @est271. I'm closing this for now in light of #456. Feel free to re-open the issue if I'm missing something.
