### ISSUE TITLE
Create tutorials of geometric statistics with geomstats

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#453]
Getting inspiration from the notebooks at: https://github.com/ageron/handson-ml,
we could create a series of 5 to 10 notebooks teaching geometric statistics through the use of geomstats.

This would re-use the code from the examples, preferably applied to real datasets.

@AliceLeBrigant you could be interested in this!

**Comment by AliceLeBrigant** [comment]
Yes, great idea. The difficulty would mostly reside in finding real datasets. @ninamiolane did you have any specific in mind ?

**Comment by Hzaatiti** [comment]
Could we start by providing jupiter notebooks (.ipynb) for each of the existing examples in geomstats ?  this could enhance the readability of the examples given that github displays notebooks really well. With some modification to sphinx, the notebooks can be displayed in the online documentation it seems as well (https://nbsphinx.readthedocs.io/en/0.5.1/)

**Comment by ninamiolane** [comment]
Yes, notebooks would be the best! And knowing that we can have them directly on the documentation with sphinx is amazing, thanks for the link.

The only reason we have not provided notebooks is that continuous integration can be tricky, and we didn't want to have potentially buggy notebooks on the GitHub. However, it seems that notebooks can be tested on Travis, for example with: 

https://github.com/ghego/travis_anaconda_jupyter

**Comment by ninamiolane** [comment]
For the datasets we have started to discuss it in issue #302 . So far, we have a `datasets` directory, but only a real dataset on graphs in provided. @AliceLeBrigant

**Comment by ninamiolane** [comment]
Let's divide the work on writing the tutorials/notebooks? @AliceLeBrigant @Hzaatiti 

- [] `01_data_on_manifolds.ipynb`: 
    - what: data examples and forbidden linear operations on manifolds
    - who: @ninamiolane 
- [] `02_from_vector_spaces_to_manifolds.ipynb`: 
    - what: metric, exp, log, geodesics, retraction, lifting
   - who: @ninamiolane

**Comment by AliceLeBrigant** [comment]
Yes ! I can do something like
- [ ] `03_basic_statistics_on_manifolds.ipynb`:
      - what: interpolation (geodesics), Fréchet mean, pca
      - who: @AliceLeBrigant 
- [ ]  `xx_information_geometry.ipynb`:
      - what: Fisher-Rao geometry of Gaussian and beta distributions
      - who: @AliceLeBrigant

**Comment by ninamiolane** [comment]
The notebooks are integrated into the documentation website! However, the webpages need to be added manually. We should make it automatic.

**Comment by Hzaatiti** [comment]
https://stackoverflow.com/questions/38526888/embed-ipython-notebook-in-sphinx-document
Would this make it automatic ?

**Comment by ninamiolane** [comment]
Maybe, I haven't tried that specifically. So far, I convert the .ipynb into .rst and the .rst constitute the pages...
https://geomstats.github.io/

The problem with my approach is that we need to add the command:
```
jupyter nbconvert --to rst --output-dir='docs' notebooks/01_data_on_manifolds.ipynb
```
somewhere, so that it is run each time we push to master.

**Comment by ninamiolane** [comment]
This has been done! 🎉
