### ISSUE TITLE
Possibly buggy imports

### ISSUE THREAD

**Issue by pchauchat** [geomstats/geomstats#500]
Tested with Tensorflow 2.0.1 and Torch1.4.0

In the definition of the backend functions, some are based on reference of Tensorflow and Torch which do not exist (in my version at least).
Maybe they worked with older/newer versions of the backends, or were used before but not anymore @ninamiolane @nkoep @pchauchat  ? That works fine because they only appear in functions, but replacing with `from blabla import name` logically breaks everything.

For tf :
- mod function 
https://github.com/geomstats/geomstats/blob/d30560da95757588328da45f71697515ba80b6c0/geomstats/backend/tensorflow/__init__.py#L89
- cross function
https://github.com/geomstats/geomstats/blob/d30560da95757588328da45f71697515ba80b6c0/geomstats/backend/tensorflow/__init__.py#L300

For Pytorch :
- __version__ : 
https://github.com/geomstats/geomstats/blob/d30560da95757588328da45f71697515ba80b6c0/geomstats/backend/pytorch/__init__.py#L64
- greater_equal
https://github.com/geomstats/geomstats/blob/d30560da95757588328da45f71697515ba80b6c0/geomstats/backend/pytorch/__init__.py#L232
- average
https://github.com/geomstats/geomstats/blob/d30560da95757588328da45f71697515ba80b6c0/geomstats/backend/pytorch/__init__.py#L271
- hsplit
https://github.com/geomstats/geomstats/blob/d30560da95757588328da45f71697515ba80b6c0/geomstats/backend/pytorch/__init__.py#L388
- cov
https://github.com/geomstats/geomstats/blob/d30560da95757588328da45f71697515ba80b6c0/geomstats/backend/pytorch/__init__.py#L408

**Comment by nguigs** [comment]
This was solved
