### ISSUE TITLE
Inconsistent behavior of gs.array

### ISSUE THREAD

**Issue by pchauchat** [geomstats/geomstats#511]
It seems gs.array behaves differently in Pytorch compared to Numpy and Tensorflow :
https://github.com/geomstats/geomstats/blob/6cf2aba8f917718028e445207eb3705fb56c98ab/geomstats/geometry/special_orthogonal.py#L298

Numpy and Tensorflow will transform the line into a (usually) 3D array, while Pytorch creates a 2D array. This is, as it is a list of tensors, it concatenates them along the first dimension.

I though ot calling to_ndarray before, but since it starts by calling array, it will loop. 
Edit on a possible solution: replace `val = concatenate(val)` by `val = stack(val)`, which looks more appropriate.

Another question is also whether that was intended, and if yes, what does it break ?

**Comment by nguigs** [comment]
It would be helpful to pass a `dtype` argument to `gs.array` as well! It's already the case with numpy and tf, it would be nice to add it to pytorch

**Comment by pchauchat** [comment]
I forgot to mention this issue again in the last two PRs, which propose a solution for the question of the `array` function, and add the `dtype` argument. This however required some machinery, which you may want to discuss : #574  #575

**Comment by lpereira95** [comment]
I believe #1550 solved all the inconsistencies. If in the meantime we find an unexpected behavior, we can reopen this.
