### ISSUE TITLE
Exponential Barycenter method in LieGroups

### ISSUE THREAD

**Issue by nguigs** [geomstats/geomstats#531]
https://github.com/geomstats/geomstats/blob/9c3dd5095d4cefba3a34f53249e68b33f9020af6/geomstats/geometry/lie_group.py#L400
Do we want to keep this method here? In spirit it is very close to `FrechetMean` estimator, which is now in `learning`, with the difference that it uses canonical group operations (`exp, log`) rather than the Riemannian ones.

The method is implemented here for instance
https://github.com/geomstats/geomstats/blob/9c3dd5095d4cefba3a34f53249e68b33f9020af6/geomstats/geometry/special_euclidean.py#L767
But it can be factorized to the above to be available to all groups. I fixed it a while ago because I needed it on `SEn` but haven't pushed it. Should it remain a `LieGroup` method or should it be moved to the `learning` module?

**Comment by ninamiolane** [comment]
Well spotted! I'd say we put it in the `learning` module, just as FrechetMean is, as you suggested.
