### ISSUE TITLE
Rename 'diag' function in backends

### ISSUE THREAD

**Issue by nkoep** [geomstats/geomstats#545]
The `diag` function in the backends behaves very differently from numpy's `diag` function. Given a matrix of size m-by-n, the function currently returns an array/tensor of size m-by-n-by-n, where each n-by-n subarray is a diagonal matrix formed by the rows of the input matrix.

Since the backends are supposed to follow numpy's API, the function should be renamed to emphasize this difference in behavior.

**Comment by ythanwerdas** [comment]
I agree with you. Moreover, that is exactly what `from_vector_to_diagonal_matrix` does now (and for the three backends).
