### ISSUE TITLE
Inconsitent behavior of gs.split

### ISSUE THREAD

**Issue by nguigs** [geomstats/geomstats#567]
With numpy backend:
```python
>>> gs.split(gs.arange(13), gs.array([2, 5]))
[array([0, 1]), array([2, 3, 4]), array([ 5,  6,  7,  8,  9, 10, 11, 12])]
```
This behavior can be useful e.g. to split according to a cumulative sum (in product_manifold). Whereas with pytorch:
```python
>>> gs.split(gs.arange(13), gs.array([2, 5]))
TypeError: split_with_sizes(): argument 'split_sizes' (position 1) must be tuple of ints, not Tensor
```
And even
```python
>>> gs.split(gs.arange(13), (2, 5))
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 13 (input tensor's size at dimension 0)
```
Same with tf:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Determined shape must either match input shape along split_dim exactly if fully specified, or be less than the size of the input along split_dim if not fully specified.```

**Comment by pchauchat** [comment]
If I understand correctly, , in the Numpy version the second argument provides the indices at which the split occurs ?

I had a similar problem when I wanted to adapt `hsplit` and make it consistent, I'll see if I can adapt it to `split`.

**Comment by nguigs** [comment]
Yes, but I think it can also accept a single int n to split in n equal batches

**Comment by pchauchat** [comment]
Yep, that was the main problem with `hsplit`, one version takes as input the size of the returned batches, while the other takes the number of batches, and I had to put a conversion in. I'm working on it right now, it should be done tomorrow morning
