### ISSUE TITLE
CUDA support for Riemannian exponential with PyTorch backend

### ISSUE THREAD

**Issue by systemosc** [geomstats/geomstats#843]
I am running a code on a CUDA machine. I use geomstats with PyTorch backend. When I compute the Riemannian exponential of a SPD matrix `A`, for example like this:

```python3
import os; os.environ['GEOMSTATS_BACKEND'] = 'pytorch'
from geomstats.geometry.spd_matrices import SPDMetricAffine
A = torch.rand(4, 4)
A = A @ A.T # make it SP(D)
A = A.to('cuda')
metric = SPDMetricAffine(4)
A = metric.exp(A, A)
```

I get the following error: `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

Do you know any workaround for this?

**Comment by ninamiolane** [comment]
Hi @systemosc thank you for your interest!

It might come from the fact that the eigenvalues decomposition required for the Riemannian exponential calls:
https://github.com/geomstats/geomstats/blob/4aab934ccb57b5fb0524f69f20d0aa76d910222f/geomstats/_backend/pytorch/linalg.py#L37

^ where `np.linalg.eigh` is called. 👎 

We obviously have tried to change this, but I don't remember what was the exact issue with our attempts.

@ythanwerdas, @nguigs  do you remember what is the status/issue on using torch (and tf) for the eigenvalues decomposition?

@systemosc you're welcome to try to change it too in the meantime, and I can assist you in the PRs.

This should be useful:
https://pytorch.org/docs/master/generated/torch.eig.html
https://pytorch.org/docs/master/generated/torch.symeig.html

**Comment by cshewmake2** [comment]
If I understand correctly, part of the reason for this workaround over to numpy.linalg.expm or scipy was because pytorch still doesn't have the matrix exponential implemented. 

In the case of the symmetric matrices, I think we can just use torch.symeig. A few simple tests against numpy seem to show equivalence with the right arguments.

I've raised a PR for this here #844 
More generally, we still need to accommodate the matrix exponential function fully in pytorch. This will be hard until pytorch releases that function itself.

**Comment by systemosc** [comment]
Thanks @ninamiolane @cshewmake2 for your help!
I thinks @cshewmake2's solution is OK for symmetric matrices, isn't it?
Should fix what I need
Thanks a lot all

**Comment by cshewmake2** [comment]
Hi @systemosc. Please let me know if the problem persists! Thanks for raising the issue.

**Comment by systemosc** [comment]
![image](https://user-images.githubusercontent.com/67270428/88636287-fd45ee80-d0b8-11ea-93c9-bc5d1c663d5e.png)
In fact, the error persists
It might have to do with pytorch internals.

**Comment by systemosc** [comment]
Hi,
There is still an error (I changed the code of `eigh` as you did @cshewmake2 ):
![image](https://user-images.githubusercontent.com/67270428/88637639-b8bb5280-d0ba-11ea-8ef3-ffea8780337f.png)
Still trying to run the following code:
```python3
import os, torch; os.environ['GEOMSTATS_BACKEND'] = 'pytorch'
from geomstats.geometry.spd_matrices import SPDMetricAffine

A = torch.rand(4, 4)
A = A @ A.T  # make it SP(D)
A = A.to('cuda')
metric = SPDMetricAffine(4)
A = metric.exp(A, A)
```

**Comment by cshewmake2** [comment]
Thanks for this @systemosc. Looking into it now.

**Comment by cshewmake2** [comment]
Okay, so here's a quick workaround that may help you in the mean time. I think the error has something to do with tensors that are created for auxiliary computations in the backend. These tensors live on the CPU by default, which could explain the error--trying to interact with data in different places.

So, if you specify ahead of time that all tensors should be written to the cuda device by default, then it works.
Try inserting this line just after your package imports

`torch.set_default_tensor_type('torch.cuda.FloatTensor')`

Of course you can use a different precision if you like.
I'll look into what's happening internally in the mean time.

**Comment by systemosc** [comment]
Indeed, it works well @cshewmake2 
Thanks a lot for your help
I'll use that after the `if torch.cuda.is_available`

**Comment by anonymously-register** [comment]
Hi, I found this function **Hypersphere(emb_size).metric.dist(a, b)** also throws such errors: 
RuntimeError: Expected tensor to have cuda DeviceType, but got tensor with cpu DeviceType (while checking arguments for einsum():)

**Comment by ninamiolane** [comment]
@anonymously-register thanks for reaching out! Just making sure: what are `a.device` and `b.device` in your example?
