### ISSUE TITLE
Geodesic regression

### ISSUE THREAD

**Issue by kristianeschenburg** [geomstats/geomstats#845]
Hi Geomstats dev team --

I'm interested in performing geodesic regression on the Grassmann manifold (see this [paper](https://www.sci.utah.edu/publications/fletcher11/Fletcher_MFCA2011.pdf) by Thomas Fletcher).  I have dependent variables Y sampled from this manifold, where each sample Y_i is in ( R^{n x k} ).  For each Y_i, I also have a vector of scalar-valued independent variables, X_i, (like age, sex, other demographic information).

I'm hoping to use Geomstats to fit the regression of Y ~ X but am unsure of how to go about doing this.  It seems that the ML tutorials assume the manifold-valued data will be used as the independent, rather than dependent, variable.

Any help is much appreciated.

**Comment by ninamiolane** [comment]
Hi (again!) @kristianeschenburg ! Thank you for your interest. 

I think @nguigs was interested in geodesic regression too, I will let him answer.

**Comment by nguigs** [comment]
Hi!

You are right, this kind of problems with dependent variable living in a manifold are not yet treated. I am currently implementing geodesic regression and have a working example on the hypersphere, that I can share with you if you want. However, some tools are missing for the Grassmannian (e.g. projection, to_tangent) but I will do this in the coming days.

Note however that in the model of Fletcher et al. from the above paper, there is only one independent variable, i.e. X_i \in \R, which acts as the affine/time parameter of the regression geodesic.

**Comment by kristianeschenburg** [comment]
Thanks for the info!  Yes I saw that the Fletcher paper assumes one independent variable.  I think for my purposes, that would work.  There was an additional paper by Hyunwoo Kim et al. applied to multiple regression, that makes the explicit assumption that the fitted intercept point is the Frechet mean of Y, based on some empirical observations, though this is obviously a heuristic approach.

**Comment by nguigs** [comment]
Yes, I would refer to this approximation by Hyunwoo Kim et al. as tangent linear regression, (similarly to tangent PCA). It is possible to do this in geomstats by using the preprocessing module, this is exemplified in the [notebook #3](https://github.com/geomstats/geomstats/blob/master/notebooks/03_simple_machine_learning_tangent_spaces.ipynb). Please let me know if you encounter issues running it on the Grassmann manifold.

**Comment by nguigs** [comment]
#847 should help

**Comment by nguigs** [comment]
Hi, here is [a first attempt](https://github.com/nguigs/geomstats/blob/nguigs-regression/examples/geodesic_regression_grassmann.py) at fitting a geodesic regression model on randomly sampled data. The optimization does not quite work yet but I am still other strategies.

**Comment by kellertuer** [comment]
Hi,
may I asked for a few explanations and details on the first attempt? I think the full model from Thomas Fletchers paper requires two optimization variable (start point / base point of a geodesic and a direction), and you might want to use a method on the tangent bundle then.
I am just not 100% familiar with python and scipy on this, that's why I am asking (I mainly do Julia, but optimization on manifolds therein).

**Comment by nguigs** [comment]
Hi @kellertuer, you are absolutely right, but I had such convergence issues that I simplified the problem to estimate only the initial velocity of the regression geodesic (beta in the script). I pushed[ another example](https://github.com/nguigs/geomstats/blob/nguigs-regression/examples/geodesic_regression_hypersphere.py) on the hypersphere, where the base point is optimized (and called the intercept). Let me know if you have any feedback on either example!

**Comment by kellertuer** [comment]
Without having run this, that looks quite good, I would just have expected a parallel transport of the beta part within the model and/or gradient; but if you don't move that far the projection that you do might be a good enough approximation, so then it should work, I think.

**Comment by nguigs** [comment]
I can see the use of parallel transport to propagate the noise (instead of projecting to the tangent space of each point), but I don't see why it should appear for the beta part? Beta is the initial velocity of the geodesic we're looking for. Do you mean that the gradient computed with autodiff is not a Riemannian gradient? I will also compare with a more intrinsic optimization strategy

**Comment by kellertuer** [comment]
The start point where this velocity is at should be able to move according to Tom Fletcher, i.e. the base point should be part of the optimization too (initialising it to the mean is fine, for sure). When the base point moves, you have to parallel transport (or vector transport) the velocity to the new base point, too.

**Comment by nguigs** [comment]
Aaaah ok thanks! So it's in the update of the parameters during optimization.

**Comment by kellertuer** [comment]
And locally it should be fine for most manifolds to maybe just project onto the new tangent space (as a vector transport) instead of a parallel transport.
This work for all manifolds that are embedded.

**Comment by oleg-kachan** [comment]
Any update on this?

**Comment by nguigs** [comment]
Yes, I am waiting for #922 and automatic differentiation to be factorized to push an update of [this](https://github.com/nguigs/geomstats/blob/nguigs-regression/examples/geodesic_regression_grassmann.py).

**Comment by kellertuer** [comment]
I just finished my first part of a tutorial (though in Julia) on Geodesic Regression, see

https://manoptjl.org/previews/PR79/tutorials/GeodesicRegression.html

where the thin black lines are by a coordinate PCA in the tangent space of the mean, but if you want to reduce the squared error of the data to (fixed time points on) the geodesic – an algorithm like the gradient descent proposed by Tom Fletcher helps.

And sure, with AD as mentioned, the adjoint of the differential of the exponential map with respect to base point and/or argument is the main thing required (compare Formulae 7 and 8 in the paper by Fletcher). 

Maybe this gives some nice insight, though it is not Python code.

And a draw back is stated in the end currently, where I still plan to continue...
