### ISSUE TITLE
Empirical Frechet Mean example not working with Tensorflow and PyTorch backends 

### ISSUE THREAD

**Issue by ahenkes1** [geomstats/geomstats#867]
Trying "empirical_frechet_mean_uncertainty_sn.py " from /examples, I only get it running using `export GEOMSTATS_BACKEND=numpy`.

For `export GEOMSTATS_BACKEND=tensorflow` I get the following error:

`  File "empirical_frechet_mean_uncertainty_sn.py", line 219, in <module>
    main()
  File "empirical_frechet_mean_uncertainty_sn.py", line 196, in main
    1, 0.1, 2, n_expectation=n_expectation)))
  File "empirical_frechet_mean_uncertainty_sn.py", line 56, in empirical_frechet_var_bubble
    north_pole[dim] = 1.0
TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment
`

And for  `export GEOMSTATS_BACKEND=pytorch` I get the following:

`  File "empirical_frechet_mean_uncertainty_sn.py", line 219, in <module>
    main()
  File "empirical_frechet_mean_uncertainty_sn.py", line 196, in main
    1, 0.1, 2, n_expectation=n_expectation)))
  File "empirical_frechet_mean_uncertainty_sn.py", line 75, in empirical_frechet_var_bubble
    return gs.mean(var), 2 * gs.std(var) / gs.sqrt(n_expectation)
TypeError: mean(): argument 'input' (position 1) must be Tensor, not list
`

**Comment by nguigs** [comment]
Hi! Thank you for trying geomstats. Indeed, the purpose of this example is to illustrate [a paper](https://hal.inria.fr/hal-02157952) studying the behaviour of the Frechet mean estimator, and it is only implemented for numpy. The Frechet mean estimator does work for all backends in general. Please have a look at the other examples if you want to use Tensorflow and Pytorch.

**Comment by ahenkes1** [comment]
Thank you very much for the quick reply.
