### ISSUE TITLE
Parallelize geometry.riemannian_metric.dist_pairwise

### ISSUE THREAD

**Issue by oleg-kachan** [geomstats/geomstats#880]
dist_pairwise is implemented using for loop, thus is single-threaded and slow, this could be fixed to use all available processor threads.

Also method signature contains a hint "Set of points in _hyperbolic_ space" - to be corrected to points of the arbitrary manifold which metric is specified.

**Comment by ninamiolane** [comment]
@tgeral68 @Hzaatiti any thoughts on this?
