### ISSUE TITLE
PoincareBall(..).metric.geodesic(...)(gs.linspace(....)) fails

### ISSUE THREAD

**Issue by pulquero** [geomstats/geomstats#893]
For other manifolds, this works fine, the exception being PoincareBall. The cause seems to be the presence of this decorator:
    
@geomstats.vectorization.decorator(['else', 'vector', 'vector'])
    def exp(self, tangent_vec, base_point):

that isn't present on the exp() method of any of the other metric classes.

**Comment by ninamiolane** [comment]
Thank you for pointing this out! @tgeral68 @Hzaatiti let me know if you want to give this a try? Otherwise I can have a look but not this week unfortunately.

**Comment by ninamiolane** [comment]
@pulquero , you can have a look at the ongoing PR #896 (thanks to @tgeral68 )!

**Comment by ninamiolane** [comment]
Solved by #896
