### ISSUE TITLE
PoincareBallMetric.mobius_add() doesn't support passing through tolerance value to belongs()

### ISSUE THREAD

**Issue by pulquero** [geomstats/geomstats#894]
PoincareBallMetric.geodesic() and mobius_add() have no support for specifying the tolerance to use for belongs() checks. Something like **kwargs should be added to the method signatures and passed through.

**Comment by ninamiolane** [comment]
Hi @pulquero thank you for your interest and feedback! @tgeral68 @Hzaatiti do you want to have a look at this?

**Comment by ninamiolane** [comment]
@pulquero , you can have a look at the ongoing PR #896 (thanks to @tgeral68 )

**Comment by ninamiolane** [comment]
Solved by #896
