### ISSUE TITLE
As a end user, I would like to see documentation for module 'datasets' under API reference

### ISSUE THREAD

**Issue by SaitejaUtpala** [geomstats/geomstats#931]
There is documentation for four modules under API reference. 

- geometry
- learning
- backend
- visualization

But why is there no documentation for 'datasets' module ? It would really be nice to have documentation for datasets here

**Comment by ninamiolane** [comment]
Well spotted! I am not sure what is happening there... @cshewmake2 would you know? Is the API-reference html page not updated automatically?

**Comment by cshewmake2** [comment]
Great idea @SaitejaUtpala! All we need to do is add `datasets` to the sphinx build. I'll look into it!

**Comment by SaitejaUtpala** [comment]
@cshewmake2  also why are we not using github-actions for CI/CD pipeline. because travis-CI has cancelled free access to open source starting last december and provides just 1k minutes credit.

**Comment by ninamiolane** [comment]
Fixed by #950 thanks to @SaitejaUtpala !
