### ISSUE TITLE
Use GitHub-actions instead of travis for CI

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#960]
Following the excellent recommendation of @SaitejaUtpala .

It seems that travis-CI cancelled free acess for open source repos :face_with_rolling_eyes: ! starting from 2020 December. (see here for official news https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing ) . Also they are mentioning that "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information." on official site. 

Github actions can be used to test on GPUs , see how pytorch-lightning implements it here:
Rehttps://medium.com/pytorch/how-pytorch-lightning-became-the-first-ml-framework-to-runs-continuous-integration-on-tpus-a47a882b2c95 about how they used github actions to test TPUS and why they have chosen github actions.

Another useful link: https://stackoverflow.com/questions/59759921/how-to-skip-github-actions-job-on-push-event

**Comment by SaitejaUtpala** [comment]
@ninamiolane  I will be working on this issue. Any suggestions are welcome !!
